<?php
/**
 * 🏗️ EE Page Builder v2 — a Wix/Canva-style visual builder for non-coders.
 *
 * What non-coders get:
 *  - A live WYSIWYG canvas: the page renders EXACTLY as the frontend while
 *    you edit (same PHP renderer via ajax — single source of truth).
 *  - Click any element on the canvas to select it; click its text to type
 *    directly into the page (inline editing).
 *  - Desktop / tablet / mobile preview switch, undo/redo (Ctrl+Z),
 *    duplicate/delete/reorder, WP media-library image picker,
 *    one-click starter templates, copy/paste (export/import) of layouts.
 *  - 17 ready-made elements + every element has Background (white/soft/navy)
 *    and Spacing controls. Everything is locked to the design system
 *    (Inter · #19335D · #DE6E30 · white) and fully responsive.
 *
 * Admin:   ExtraaEdge Site → 🏗️ Page Builder
 * Storage: _ee_pb_json + _ee_pb_on per page
 * Render:  template_include → page-builder-canvas.php when _ee_pb_on
 *
 * @package ExtraaEdge
 */
if (!defined('ABSPATH')) exit;

/* =========================================================================
 * 1. Element registry.
 *    type => [label, emoji, fields]; field:
 *    key => [label, input(text|textarea|url|select|number|check), default,
 *            options(for select)]
 * ========================================================================= */
function ee_pb_elements() {
    $sections = function_exists('ee_home_sections_registry') ? ee_home_sections_registry() : array();
    $sec_opts = array();
    foreach ($sections as $id => $meta) { $sec_opts[$id] = $meta[0]; }
    return array(
        'html' => array('Paste HTML Page', '📥', array(
            'code' => array('Paste a full HTML page here (e.g. a landing page generated by Claude AI). It renders exactly as-is, isolated from the theme — and its text stays editable right on the canvas.', 'code', ''),
        )),
        'hero' => array('Hero', '🦸', array(
            'eyebrow'  => array('Eyebrow label', 'text', 'WELCOME'),
            'heading'  => array('Heading', 'text', 'Your big headline here'),
            'sub'      => array('Sub text', 'textarea', 'One or two supporting sentences that explain the value.'),
            'btn_text' => array('Button text', 'text', 'Book a Demo'),
            'btn_link' => array('Button link', 'url', '/book-demo/'),
            'align'    => array('Alignment', 'select', 'center', array('center' => 'Center', 'left' => 'Left')),
        )),
        'heading' => array('Heading', '🔤', array(
            'text'  => array('Text', 'text', 'Section heading'),
            'level' => array('Size', 'select', 'h2', array('h1' => 'H1 (largest)', 'h2' => 'H2', 'h3' => 'H3')),
            'align' => array('Alignment', 'select', 'center', array('center' => 'Center', 'left' => 'Left')),
        )),
        'text' => array('Text', '📄', array(
            'content' => array('Paragraph text (blank line = new paragraph)', 'textarea', 'Write your paragraph here.'),
            'align'   => array('Alignment', 'select', 'left', array('left' => 'Left', 'center' => 'Center')),
        )),
        'image' => array('Image', '🖼️', array(
            'url'     => array('Image URL', 'url', ''),
            'alt'     => array('Alt text (SEO)', 'text', ''),
            'width'   => array('Width', 'select', '100', array('100' => 'Full', '75' => '75%', '50' => 'Half')),
            'align'   => array('Alignment', 'select', 'center', array('center' => 'Center', 'left' => 'Left')),
            'rounded' => array('Rounded corners', 'check', '1'),
        )),
        'textimg' => array('Text + Image', '📰', array(
            'heading'   => array('Heading', 'text', 'Feature heading'),
            'content'   => array('Text', 'textarea', 'Describe the feature or story here.'),
            'image'     => array('Image URL', 'url', ''),
            'image_pos' => array('Image side', 'select', 'right', array('right' => 'Right', 'left' => 'Left')),
            'btn_text'  => array('Button text (optional)', 'text', ''),
            'btn_link'  => array('Button link', 'url', '#admission-form'),
        )),
        'features' => array('Feature Cards', '🧩', array(
            'heading' => array('Heading (optional)', 'text', 'Why teams choose us'),
            'items'   => array('Cards — one per line: Title | Description', 'textarea', "Fast setup | Go live in 7 days\nAI-first | Voice, chat and WhatsApp agents\nSecure | Enterprise-grade compliance"),
            'cols'    => array('Columns', 'select', '3', array('2' => '2', '3' => '3', '4' => '4')),
        )),
        'stats' => array('Stats Row', '📊', array(
            'items' => array('Stats — one per line: Number | Label', 'textarea', "500+ | Institutions\n18M+ | Leads managed\n3.4x | Enrollment growth"),
        )),
        'testimonial' => array('Testimonial', '💬', array(
            'quote'  => array('Quote', 'textarea', 'ExtraaEdge transformed how our admission team works.'),
            'name'   => array('Name', 'text', 'Jane Doe'),
            'role'   => array('Role · Institute', 'text', 'Director · Example University'),
            'avatar' => array('Photo URL (optional)', 'url', ''),
        )),
        'video' => array('YouTube Video', '▶️', array(
            'url'     => array('YouTube link or video ID', 'text', ''),
            'heading' => array('Heading (optional)', 'text', ''),
        )),
        'logos' => array('Logo Strip', '🏛️', array(
            'heading' => array('Heading (optional)', 'text', 'Trusted by leading institutions'),
            'items'   => array('Logo image URLs — one per line', 'textarea', ''),
        )),
        'pricing' => array('Pricing Cards', '💳', array(
            'heading' => array('Heading (optional)', 'text', 'Simple pricing'),
            'items'   => array("Plans — one per line:\nName | Price | feature; feature; feature | Button text | Button link | featured", 'textarea', "Starter | ₹4,999/mo | Lead management; WhatsApp; Email | Get started | /book-demo/\nGrowth | ₹9,999/mo | Everything in Starter; AI scoring; Voice agent | Get started | /book-demo/ | featured\nEnterprise | Custom | Everything in Growth; SSO; Dedicated support | Talk to us | /book-demo/"),
        )),
        'faq' => array('FAQ Accordion', '❓', array(
            'heading' => array('Heading (optional)', 'text', 'Frequently asked questions'),
            'items'   => array('FAQs — one per line: Question | Answer', 'textarea', "How fast can we go live? | Most teams launch in about 7 days.\nDo you migrate our data? | Yes - migration and onboarding are included."),
        )),
        'cta' => array('CTA Banner', '📣', array(
            'heading'  => array('Heading', 'text', 'Ready to convert more students?'),
            'sub'      => array('Sub text', 'text', 'See ExtraaEdge on your funnel in 30 minutes.'),
            'btn_text' => array('Button text', 'text', 'Book a Demo'),
            'btn_link' => array('Button link', 'url', '/book-demo/'),
        )),
        'button' => array('Button', '🔘', array(
            'text'  => array('Text', 'text', 'Learn more'),
            'link'  => array('Link', 'url', '#'),
            'style' => array('Style', 'select', 'solid', array('solid' => 'Orange solid', 'outline' => 'Navy outline')),
            'align' => array('Alignment', 'select', 'center', array('center' => 'Center', 'left' => 'Left')),
        )),
        'spacer' => array('Spacer', '↕️', array(
            'height' => array('Height (px)', 'number', '48'),
        )),
        'divider' => array('Divider', '➖', array()),
        'homesec' => array('Homepage Section', '🏠', array(
            'section' => array('Section', 'select', 'feature-pillars', $sec_opts),
            'heading' => array('Override heading (optional)', 'text', ''),
            'sub'     => array('Override sub text (optional)', 'text', ''),
            'eyebrow' => array('Override eyebrow (optional)', 'text', ''),
        )),
    );
}

/** Style controls every element gets (Wix-style section settings). */
function ee_pb_style_fields() {
    return array(
        '_bg'  => array('Background', 'select', 'white', array('white' => 'White', 'soft' => 'Soft grey', 'navy' => 'Navy (dark)')),
        '_pad' => array('Spacing', 'select', 'm', array('s' => 'Compact', 'm' => 'Normal', 'l' => 'Spacious')),
    );
}

/* =========================================================================
 * 2. Sanitize a submitted layout — only known elements/fields survive.
 * ========================================================================= */
function ee_pb_sanitize_items($raw) {
    $reg   = ee_pb_elements();
    $style = ee_pb_style_fields();
    $out   = array();
    if (!is_array($raw)) return $out;
    foreach (array_slice($raw, 0, 200) as $item) {
        $t = isset($item['t']) ? sanitize_key($item['t']) : '';
        if (!isset($reg[$t])) continue;
        $s = array();
        foreach (array_merge($reg[$t][2], $style) as $key => $field) {
            $v = isset($item['s'][$key]) ? $item['s'][$key] : $field[2];
            switch ($field[1]) {
                /* raw pasted HTML — admin-only save path (like WP's Custom
                   HTML widget); rendered inside a sandboxed iframe. Scrub any
                   editing scaffolding that older builds baked into the code. */
                case 'code':
                    $v = mb_substr((string) $v, 0, 500000);
                    $v = preg_replace('#<style id="__eepb_pv_fix">.*?</style>#s', '', $v);
                    $v = preg_replace('#<script id="__eepb_rescue">.*?</script>#s', '', $v);
                    $v = str_replace(array(' contenteditable="true"', " contenteditable='true'", ' spellcheck="false"', '__eepb_sel', '__eepb_hov'), '', $v);
                    break;
                case 'url':      $v = esc_url_raw(trim((string) $v)); break;
                case 'number':   $v = (string) max(0, min(400, (int) $v)); break;
                case 'check':    $v = $v ? '1' : ''; break;
                case 'select':
                    $opts = isset($field[3]) ? $field[3] : array();
                    if (!isset($opts[$v])) { $v = $field[2]; }
                    break;
                case 'textarea': $v = sanitize_textarea_field(mb_substr((string) $v, 0, 8000)); break;
                default:         $v = sanitize_text_field(mb_substr((string) $v, 0, 600));
            }
            $s[$key] = $v;
        }
        $out[] = array('t' => $t, 's' => $s);
    }
    return $out;
}

/* =========================================================================
 * 3. Renderer — brand-locked, fully escaped, shared by frontend + preview.
 * ========================================================================= */
function ee_pb_split_lines($txt) {
    $rows = array();
    foreach (preg_split('/\r?\n/', (string) $txt) as $line) {
        $line = trim($line);
        if ($line === '') continue;
        $rows[] = array_map('trim', explode('|', $line));
    }
    return $rows;
}

/** Escapes a value; in preview mode wraps it so it is inline-editable. */
function ee_pb_txt($val, $key, $preview) {
    $out = esc_html($val);
    return $preview ? '<span data-edit="' . esc_attr($key) . '">' . $out . '</span>' : $out;
}

function ee_pb_css() {
    return '<style id="ee-pb-css">
.eepb{font-family:\'Inter\',-apple-system,BlinkMacSystemFont,sans-serif;color:#19335D;background:#fff;line-height:1.55;-webkit-font-smoothing:antialiased}
.eepb *{box-sizing:border-box}
.eepb .pbw{max-width:1140px;margin:0 auto;padding:0 22px}
.eepb .pb-el{padding:26px 0}
.eepb .pb-wrap.pad-s .pb-el{padding:10px 0}
.eepb .pb-wrap.pad-l .pb-el{padding:52px 0}
.eepb .pb-wrap.bg-soft{background:#f5f7fb}
.eepb .pb-wrap.bg-navy{background:linear-gradient(135deg,#19335D,#20406e)}
.eepb .pb-wrap.bg-navy h1,.eepb .pb-wrap.bg-navy h2,.eepb .pb-wrap.bg-navy h3,.eepb .pb-wrap.bg-navy summary{color:#fff!important}
.eepb .pb-wrap.bg-navy p,.eepb .pb-wrap.bg-navy .pb-feat span,.eepb .pb-wrap.bg-navy .pb-stat span{color:rgba(255,255,255,.78)!important}
.eepb .pb-wrap.bg-navy .pb-feat,.eepb .pb-wrap.bg-navy .pb-stat,.eepb .pb-wrap.bg-navy .pb-faq details,.eepb .pb-wrap.bg-navy .pb-price{background:rgba(255,255,255,.06);border-color:rgba(255,255,255,.16)}
.eepb .pb-wrap.bg-navy .pb-feat b,.eepb .pb-wrap.bg-navy .pb-price b.nm{color:#fff}
.eepb .ta-center{text-align:center}.eepb .ta-left{text-align:left}
.eepb h1,.eepb h2,.eepb h3{font-weight:800;letter-spacing:-.02em;line-height:1.15;color:#19335D;margin:0}
.eepb .pb-h1{font-size:clamp(32px,4.6vw,52px)}.eepb .pb-h2{font-size:clamp(26px,3.2vw,38px)}.eepb .pb-h3{font-size:clamp(20px,2.4vw,26px)}
.eepb p{margin:0;font-size:16.5px;color:rgba(25,51,93,.78)}
.eepb .pb-eyebrow{display:inline-block;font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#DE6E30;margin-bottom:14px}
.eepb .pb-btn{display:inline-flex;align-items:center;gap:8px;font-weight:700;font-size:15px;padding:13px 26px;border-radius:999px;text-decoration:none;transition:transform .2s,box-shadow .2s,background .2s}
.eepb .pb-btn--solid{background:#DE6E30;color:#fff;box-shadow:0 10px 24px -10px rgba(222,110,48,.55)}
.eepb .pb-btn--solid:hover{transform:translateY(-2px);background:#c85d20;color:#fff}
.eepb .pb-btn--outline{background:#fff;color:#19335D;border:2px solid #19335D}
.eepb .pb-btn--outline:hover{background:#19335D;color:#fff}
.eepb .pb-hero{padding:56px 0 40px}
.eepb .pb-hero .sub{max-width:640px;font-size:clamp(16px,1.6vw,18.5px);margin-top:14px}
.eepb .pb-hero.ta-center .sub{margin-left:auto;margin-right:auto}
.eepb .pb-hero .act{margin-top:26px}
.eepb .pb-img{display:block;max-width:100%;height:auto}
.eepb .pb-img--rounded{border-radius:18px}
.eepb .pb-textimg{display:grid;grid-template-columns:1fr 1fr;gap:44px;align-items:center}
.eepb .pb-textimg .txt h2{margin-bottom:12px}
.eepb .pb-textimg .txt .act{margin-top:20px}
.eepb .pb-textimg img{width:100%;height:auto;border-radius:18px;display:block}
.eepb .pb-feats{display:grid;gap:18px}
.eepb .pb-feats.cols-2{grid-template-columns:repeat(2,1fr)}.eepb .pb-feats.cols-3{grid-template-columns:repeat(3,1fr)}.eepb .pb-feats.cols-4{grid-template-columns:repeat(4,1fr)}
.eepb .pb-feat{background:#fff;border:1px solid #e7ecf3;border-radius:16px;padding:22px;transition:box-shadow .25s,transform .25s}
.eepb .pb-feat:hover{transform:translateY(-3px);box-shadow:0 16px 34px -16px rgba(25,51,93,.22)}
.eepb .pb-feat b{display:block;font-size:16.5px;font-weight:800;color:#19335D;margin-bottom:7px}
.eepb .pb-feat span{font-size:14px;color:rgba(25,51,93,.72);line-height:1.55}
.eepb .pb-feats-h,.eepb .pb-sec-h{margin-bottom:22px;text-align:center}
.eepb .pb-stats{display:flex;flex-wrap:wrap;justify-content:center;gap:16px}
.eepb .pb-stat{flex:1 1 180px;max-width:260px;text-align:center;background:#fff;border:1px solid #e7ecf3;border-radius:16px;padding:24px 16px}
.eepb .pb-stat b{display:block;font-size:clamp(30px,3.4vw,42px);font-weight:800;color:#DE6E30;line-height:1.05}
.eepb .pb-stat span{display:block;margin-top:7px;font-size:13.5px;font-weight:600;color:rgba(25,51,93,.75)}
.eepb .pb-testi{max-width:720px;margin:0 auto;text-align:center}
.eepb .pb-testi .q{font-size:clamp(18px,2.2vw,23px);font-weight:600;line-height:1.5;color:#19335D}
.eepb .pb-testi .q::before{content:"\201C";color:#DE6E30;font-weight:800}
.eepb .pb-testi .q::after{content:"\201D";color:#DE6E30;font-weight:800}
.eepb .pb-testi .who{display:flex;align-items:center;justify-content:center;gap:12px;margin-top:18px}
.eepb .pb-testi img{width:46px;height:46px;border-radius:50%;object-fit:cover;box-shadow:0 0 0 2px #DE6E30}
.eepb .pb-testi b{font-weight:800;font-size:15px}
.eepb .pb-testi i{font-style:normal;font-size:12.5px;color:rgba(25,51,93,.6);display:block;margin-top:2px}
.eepb .pb-video{position:relative;max-width:860px;margin:0 auto;aspect-ratio:16/9;border-radius:18px;overflow:hidden;background:#0d1c33}
.eepb .pb-video iframe{position:absolute;inset:0;width:100%;height:100%;border:0}
.eepb .pb-logos{display:flex;flex-wrap:wrap;justify-content:center;align-items:center;gap:34px}
.eepb .pb-logos img{height:34px;width:auto;object-fit:contain}
.eepb .pb-prices{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px;max-width:980px;margin:0 auto}
.eepb .pb-price{background:#fff;border:1px solid #e7ecf3;border-radius:18px;padding:26px 22px;display:flex;flex-direction:column;text-align:center}
.eepb .pb-price.hot{border-color:#DE6E30;box-shadow:0 18px 40px -18px rgba(222,110,48,.4);position:relative}
.eepb .pb-price.hot::before{content:"POPULAR";position:absolute;top:-10px;left:50%;transform:translateX(-50%);background:#DE6E30;color:#fff;font-size:10px;font-weight:800;letter-spacing:.08em;padding:3px 12px;border-radius:99px}
.eepb .pb-price b.nm{font-size:16px;font-weight:800;color:#19335D}
.eepb .pb-price .pr{font-size:clamp(24px,2.6vw,32px);font-weight:800;color:#DE6E30;margin:10px 0 14px}
.eepb .pb-price ul{list-style:none;margin:0 0 18px;padding:0;display:flex;flex-direction:column;gap:8px;flex:1}
.eepb .pb-price li{font-size:13.5px;color:rgba(25,51,93,.75)}
.eepb .pb-price li::before{content:"\2713  ";color:#DE6E30;font-weight:800}
.eepb .pb-faq{max-width:760px;margin:0 auto}
.eepb .pb-faq details{border:1px solid #e7ecf3;border-radius:12px;background:#fff;margin-bottom:10px;overflow:hidden}
.eepb .pb-faq summary{cursor:pointer;list-style:none;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:15px 18px;font-weight:700;font-size:15.5px;color:#19335D}
.eepb .pb-faq summary::-webkit-details-marker{display:none}
.eepb .pb-faq summary::after{content:"+";font-size:20px;font-weight:800;color:#DE6E30;flex:none;line-height:1}
.eepb .pb-faq details[open] summary::after{content:"\2212"}
.eepb .pb-faq .a{padding:0 18px 15px;font-size:14.5px;color:rgba(25,51,93,.75);line-height:1.6}
.eepb .pb-cta{background:linear-gradient(135deg,#19335D,#22467c);border-radius:22px;padding:clamp(28px,4vw,48px);text-align:center;color:#fff}
.eepb .pb-cta h2{color:#fff}
.eepb .pb-cta p{color:rgba(255,255,255,.78);margin-top:10px}
.eepb .pb-cta .act{margin-top:22px}
.eepb .pb-divider{border:0;border-top:1px solid #e7ecf3;margin:0}
@media(max-width:860px){
  .eepb .pb-textimg{grid-template-columns:1fr;gap:22px}
  .eepb .pb-textimg .vis{order:-1}
  .eepb .pb-feats.cols-3,.eepb .pb-feats.cols-4{grid-template-columns:repeat(2,1fr)}
}
@media(max-width:560px){
  .eepb .pb-feats.cols-2,.eepb .pb-feats.cols-3,.eepb .pb-feats.cols-4{grid-template-columns:1fr}
  .eepb .pb-el{padding:18px 0}
  .eepb .pb-logos{gap:20px}
  .eepb .pb-logos img{height:26px}
}
</style>';
}

function ee_pb_render_page($items, $preview = false) {
    $html = ee_pb_css() . '<div class="eepb">';
    foreach (array_values((array) $items) as $i => $item) {
        $el = ee_pb_render_el($item['t'], $item['s'], $preview);
        if ($preview) {
            $s   = $item['s'];
            $bg  = isset($s['_bg']) ? $s['_bg'] : 'white';
            $pad = isset($s['_pad']) ? $s['_pad'] : 'm';
            $html .= '<div class="pb-wrap pbp-item bg-' . esc_attr($bg) . ' pad-' . esc_attr($pad) . '" data-i="' . $i . '">' . $el . '</div>';
        } else {
            $s   = $item['s'];
            $bg  = isset($s['_bg']) ? $s['_bg'] : 'white';
            $pad = isset($s['_pad']) ? $s['_pad'] : 'm';
            $html .= '<div class="pb-wrap bg-' . esc_attr($bg) . ' pad-' . esc_attr($pad) . '">' . $el . '</div>';
        }
    }
    return $html . '</div>';
}

function ee_pb_render_el($t, $s, $pv = false) {
    $g = function ($k) use ($s) { return isset($s[$k]) ? $s[$k] : ''; };
    switch ($t) {

        case 'hero':
            $al = $g('align') === 'left' ? 'ta-left' : 'ta-center';
            $o  = '<section class="pb-el pb-hero ' . esc_attr($al) . '"><div class="pbw">';
            if ($g('eyebrow') !== '') $o .= '<span class="pb-eyebrow">' . ee_pb_txt($g('eyebrow'), 'eyebrow', $pv) . '</span>';
            $o .= '<h1 class="pb-h1">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h1>';
            if ($g('sub') !== '') $o .= '<p class="sub">' . ee_pb_txt($g('sub'), 'sub', $pv) . '</p>';
            if ($g('btn_text') !== '') $o .= '<div class="act"><a class="pb-btn pb-btn--solid" href="' . esc_url($g('btn_link')) . '">' . ee_pb_txt($g('btn_text'), 'btn_text', $pv) . ' →</a></div>';
            return $o . '</div></section>';

        case 'heading':
            $lv = in_array($g('level'), array('h1', 'h2', 'h3'), true) ? $g('level') : 'h2';
            $al = $g('align') === 'left' ? 'ta-left' : 'ta-center';
            return '<div class="pb-el ' . esc_attr($al) . '"><div class="pbw"><' . $lv . ' class="pb-' . $lv . '">' . ee_pb_txt($g('text'), 'text', $pv) . '</' . $lv . '></div></div>';

        case 'text':
            $al = $g('align') === 'center' ? 'ta-center' : 'ta-left';
            $paras = '';
            foreach (preg_split('/\r?\n\r?\n/', (string) $g('content')) as $p) {
                $p = trim($p);
                if ($p !== '') $paras .= '<p style="margin-bottom:12px">' . nl2br(esc_html($p)) . '</p>';
            }
            return '<div class="pb-el ' . esc_attr($al) . '"><div class="pbw" style="max-width:820px">' . $paras . '</div></div>';

        case 'image':
            if ($g('url') === '') return $pv ? '<div class="pb-el ta-center"><div class="pbw" style="border:2px dashed #c9d4e4;border-radius:14px;padding:34px;color:#8a9bb5;font-weight:600">🖼️ Choose an image in the settings panel →</div></div>' : '';
            $w  = in_array($g('width'), array('100', '75', '50'), true) ? $g('width') : '100';
            $al = $g('align') === 'left' ? '' : 'margin-left:auto;margin-right:auto;';
            $r  = $g('rounded') ? ' pb-img--rounded' : '';
            return '<div class="pb-el"><div class="pbw"><img class="pb-img' . $r . '" style="width:' . $w . '%;' . $al . '" src="' . esc_url($g('url')) . '" alt="' . esc_attr($g('alt')) . '" loading="lazy" decoding="async"></div></div>';

        case 'textimg':
            $img = $g('image') !== ''
                ? '<div class="vis"><img src="' . esc_url($g('image')) . '" alt="' . esc_attr($g('heading')) . '" loading="lazy" decoding="async"></div>'
                : ($pv ? '<div class="vis" style="border:2px dashed #c9d4e4;border-radius:14px;padding:44px;text-align:center;color:#8a9bb5;font-weight:600">🖼️ Add an image URL</div>' : '');
            $txt = '<div class="txt"><h2 class="pb-h2">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h2><p>' . ee_pb_txt($g('content'), 'content', $pv) . '</p>';
            if ($g('btn_text') !== '') $txt .= '<div class="act"><a class="pb-btn pb-btn--solid" href="' . esc_url($g('btn_link')) . '">' . ee_pb_txt($g('btn_text'), 'btn_text', $pv) . ' →</a></div>';
            $txt .= '</div>';
            $inner = $g('image_pos') === 'left' ? $img . $txt : $txt . $img;
            return '<div class="pb-el"><div class="pbw"><div class="pb-textimg">' . $inner . '</div></div></div>';

        case 'features':
            $cols = in_array($g('cols'), array('2', '3', '4'), true) ? $g('cols') : '3';
            $o = '<div class="pb-el"><div class="pbw">';
            if ($g('heading') !== '') $o .= '<h2 class="pb-h2 pb-feats-h">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h2>';
            $o .= '<div class="pb-feats cols-' . $cols . '">';
            foreach (ee_pb_split_lines($g('items')) as $row) {
                $o .= '<div class="pb-feat"><b>' . esc_html($row[0]) . '</b><span>' . esc_html(isset($row[1]) ? $row[1] : '') . '</span></div>';
            }
            return $o . '</div></div></div>';

        case 'stats':
            $o = '<div class="pb-el"><div class="pbw"><div class="pb-stats">';
            foreach (ee_pb_split_lines($g('items')) as $row) {
                $o .= '<div class="pb-stat"><b>' . esc_html($row[0]) . '</b><span>' . esc_html(isset($row[1]) ? $row[1] : '') . '</span></div>';
            }
            return $o . '</div></div></div>';

        case 'testimonial':
            $o = '<div class="pb-el"><div class="pbw"><div class="pb-testi">';
            $o .= '<div class="q">' . ee_pb_txt($g('quote'), 'quote', $pv) . '</div>';
            $o .= '<div class="who">';
            if ($g('avatar') !== '') $o .= '<img src="' . esc_url($g('avatar')) . '" alt="' . esc_attr($g('name')) . '" loading="lazy">';
            $o .= '<span style="text-align:left"><b>' . ee_pb_txt($g('name'), 'name', $pv) . '</b><i>' . ee_pb_txt($g('role'), 'role', $pv) . '</i></span>';
            return $o . '</div></div></div></div>';

        case 'video':
            $raw = trim((string) $g('url'));
            $id  = '';
            if ($raw !== '') {
                if (preg_match('#(?:youtu\.be/|v=|/embed/|/shorts/)([A-Za-z0-9_-]{6,20})#', $raw, $m)) $id = $m[1];
                elseif (preg_match('#^[A-Za-z0-9_-]{6,20}$#', $raw)) $id = $raw;
            }
            $o = '<div class="pb-el"><div class="pbw">';
            if ($g('heading') !== '') $o .= '<h2 class="pb-h2 pb-sec-h">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h2>';
            if ($id === '') {
                $o .= $pv ? '<div style="border:2px dashed #c9d4e4;border-radius:14px;padding:44px;text-align:center;color:#8a9bb5;font-weight:600">▶️ Paste a YouTube link in the settings panel →</div>' : '';
            } else {
                $o .= '<div class="pb-video"><iframe src="https://www.youtube-nocookie.com/embed/' . esc_attr($id) . '?rel=0&amp;modestbranding=1" title="Video" loading="lazy" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div>';
            }
            return $o . '</div></div>';

        case 'logos':
            $o = '<div class="pb-el"><div class="pbw">';
            if ($g('heading') !== '') $o .= '<h2 class="pb-h3 pb-sec-h" style="font-size:clamp(15px,1.6vw,18px);letter-spacing:.05em;text-transform:uppercase;color:rgba(25,51,93,.55)">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h2>';
            $o .= '<div class="pb-logos">';
            $any = false;
            foreach (ee_pb_split_lines($g('items')) as $row) {
                $u = $row[0];
                if ($u === '') continue;
                $any = true;
                $o .= '<img src="' . esc_url($u) . '" alt="" loading="lazy" decoding="async">';
            }
            if (!$any && $pv) $o .= '<div style="border:2px dashed #c9d4e4;border-radius:14px;padding:24px 44px;color:#8a9bb5;font-weight:600">🏛️ Add logo image URLs (one per line)</div>';
            return $o . '</div></div></div>';

        case 'pricing':
            $o = '<div class="pb-el"><div class="pbw">';
            if ($g('heading') !== '') $o .= '<h2 class="pb-h2 pb-sec-h">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h2>';
            $o .= '<div class="pb-prices">';
            foreach (ee_pb_split_lines($g('items')) as $row) {
                $hot = isset($row[5]) && stripos($row[5], 'feat') !== false;
                $o .= '<div class="pb-price' . ($hot ? ' hot' : '') . '"><b class="nm">' . esc_html($row[0]) . '</b><div class="pr">' . esc_html(isset($row[1]) ? $row[1] : '') . '</div><ul>';
                foreach (explode(';', isset($row[2]) ? $row[2] : '') as $f) {
                    $f = trim($f);
                    if ($f !== '') $o .= '<li>' . esc_html($f) . '</li>';
                }
                $o .= '</ul>';
                $bt = isset($row[3]) ? $row[3] : '';
                $bl = isset($row[4]) ? $row[4] : '#';
                if ($bt !== '') $o .= '<a class="pb-btn ' . ($hot ? 'pb-btn--solid' : 'pb-btn--outline') . '" style="justify-content:center" href="' . esc_url($bl) . '">' . esc_html($bt) . '</a>';
                $o .= '</div>';
            }
            return $o . '</div></div></div>';

        case 'faq':
            $o = '<div class="pb-el"><div class="pbw"><div class="pb-faq">';
            if ($g('heading') !== '') $o .= '<h2 class="pb-h2 pb-sec-h">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h2>';
            foreach (ee_pb_split_lines($g('items')) as $row) {
                $o .= '<details><summary>' . esc_html($row[0]) . '</summary><div class="a">' . esc_html(isset($row[1]) ? $row[1] : '') . '</div></details>';
            }
            return $o . '</div></div></div>';

        case 'cta':
            $o = '<div class="pb-el"><div class="pbw"><div class="pb-cta"><h2 class="pb-h2">' . ee_pb_txt($g('heading'), 'heading', $pv) . '</h2>';
            if ($g('sub') !== '') $o .= '<p>' . ee_pb_txt($g('sub'), 'sub', $pv) . '</p>';
            if ($g('btn_text') !== '') $o .= '<div class="act"><a class="pb-btn pb-btn--solid" href="' . esc_url($g('btn_link')) . '">' . ee_pb_txt($g('btn_text'), 'btn_text', $pv) . ' →</a></div>';
            return $o . '</div></div></div>';

        case 'button':
            $st = $g('style') === 'outline' ? 'pb-btn--outline' : 'pb-btn--solid';
            $al = $g('align') === 'left' ? 'ta-left' : 'ta-center';
            return '<div class="pb-el ' . esc_attr($al) . '"><div class="pbw"><a class="pb-btn ' . $st . '" href="' . esc_url($g('link')) . '">' . ee_pb_txt($g('text'), 'text', $pv) . ' →</a></div></div>';

        case 'spacer':
            return '<div aria-hidden="true" style="height:' . (int) $g('height') . 'px"></div>';

        case 'divider':
            return '<div class="pb-el" style="padding:8px 0"><div class="pbw"><hr class="pb-divider"></div></div>';

        case 'html':
            $code = (string) $g('code');
            if (trim($code) === '') {
                return $pv ? '<div class="pb-el ta-center"><div class="pbw" style="border:2px dashed #c9d4e4;border-radius:14px;padding:44px;color:#8a9bb5;font-weight:600">📥 Paste your HTML page in the settings panel →<br><span style="font-weight:500;font-size:12.5px">e.g. a landing page generated by Claude AI (a full &lt;html&gt; file or just a fragment)</span></div></div>' : '';
            }
            if ($pv) {
                /* sandbox WITHOUT allow-scripts: the DOM stays exactly the
                   parsed markup, so canvas text edits serialize faithfully
                   (inert <script> tags are preserved in the markup).
                   Scroll-reveal pages start content at opacity:0 and rely on
                   JS to show it - with scripts off that leaves only the
                   backgrounds, so force everything visible while editing.
                   The injected style is stripped again on serialize. */
                $code_pv = $code . '<style id="__eepb_pv_fix">*{opacity:1!important;visibility:visible!important;transform:none!important;animation:none!important;transition:none!important}
.__eepb_hov{outline:2px dashed rgba(222,110,48,.6)!important;outline-offset:-2px!important;cursor:pointer!important}
.__eepb_sel{outline:2px solid #DE6E30!important;outline-offset:-2px!important}</style>';
                return '<div class="pbp-chip">📥 Pasted HTML page — click any text inside to edit it · select/delete via Layers</div>'
                     . '<iframe class="eepb-htmlpv" sandbox="allow-same-origin" srcdoc="' . esc_attr($code_pv) . '" style="display:block;width:100%;border:0;min-height:320px;overflow:hidden"></iframe>';
            }
            static $fit_done = false;
            /* Rescue for scroll-reveal pages: the iframe is content-height so
               it never scrolls, and reveal libraries that only listen to
               scroll leave everything at opacity:0. Fire scroll/resize once
               loaded; if lots of content is still invisible after 1.6s,
               force-show it. Render-time only - never stored in the code. */
            $rescue = '<script id="__eepb_rescue">(function(){function kick(){try{window.dispatchEvent(new Event("scroll"));window.dispatchEvent(new Event("resize"));document.dispatchEvent(new Event("scroll"));}catch(e){}}
if(document.readyState==="complete"){kick();}else{window.addEventListener("load",kick);}
setTimeout(kick,500);
setTimeout(function(){try{var els=document.body.getElementsByTagName("*"),hid=0;
for(var i=0;i<els.length&&hid<6;i++){var cs=getComputedStyle(els[i]);if(cs.opacity==="0"||cs.visibility==="hidden"){hid++;}}
if(hid>=3){var st=document.createElement("style");st.textContent="*{opacity:1!important;visibility:visible!important;transform:none!important}";document.head.appendChild(st);}}catch(e){}},1600);
})();</script>';
            $o = '<iframe class="eepb-htmlfr" title="Embedded page section" loading="lazy" scrolling="no"'
               . ' sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox"'
               . ' srcdoc="' . esc_attr($code . $rescue) . '"'
               . ' style="display:block;width:100%;border:0;min-height:320px;overflow:hidden"></iframe>';
            if (!$fit_done) {
                $fit_done = true;
                /* vh-safe autofit: measure with the iframe at real viewport
                   height so 100vh sections size as intended, then lock to the
                   content height. Refit only on load + window resize (no
                   ResizeObserver feedback loops with vh units). */
                $o .= '<script>(function(){if(window.__eepbHF)return;window.__eepbHF=1;
function fit(f){try{f.style.height=window.innerHeight+"px";requestAnimationFrame(function(){try{var d=f.contentDocument;if(!d||!d.body)return;var h=Math.ceil(Math.max(d.documentElement.getBoundingClientRect().height,d.body.getBoundingClientRect().height,d.documentElement.scrollHeight))+4;f.style.height=Math.max(320,Math.min(h,20000))+"px";}catch(e){}});}catch(e){}}
function all(){[].slice.call(document.querySelectorAll("iframe.eepb-htmlfr")).forEach(fit);}
[].slice.call(document.querySelectorAll("iframe.eepb-htmlfr")).forEach(function(f){f.addEventListener("load",function(){fit(f);setTimeout(function(){fit(f);},700);});if(f.contentDocument&&f.contentDocument.readyState==="complete"){fit(f);setTimeout(function(){fit(f);},700);}});
var t;window.addEventListener("resize",function(){clearTimeout(t);t=setTimeout(all,220);});
})();</script>';
            }
            return '<div class="pb-el" style="padding:0">' . $o . '</div>';

        case 'homesec':
            if ($pv) {
                $reg = function_exists('ee_home_sections_registry') ? ee_home_sections_registry() : array();
                $nm  = isset($reg[$g('section')]) ? $reg[$g('section')][0] : $g('section');
                return '<div class="pb-el ta-center"><div class="pbw" style="border:2px dashed #DE6E30;border-radius:14px;padding:34px;background:#fff7f2"><b style="color:#19335D">🏠 Homepage section: ' . esc_html($nm) . '</b><br><span style="font-size:13px;color:#8a9bb5">Shows the real section on the live page (use 👁 View).</span></div></div>';
            }
            $sc = '[ee_section id="' . esc_attr($g('section')) . '"';
            foreach (array('heading', 'sub', 'eyebrow') as $k) {
                if ($g($k) !== '') $sc .= ' ' . $k . '="' . esc_attr($g($k)) . '"';
            }
            $sc .= ']';
            return '<div class="pb-el" style="padding:10px 0">' . do_shortcode($sc) . '</div>';
    }
    return '';
}

/* =========================================================================
 * 4. Frontend hookup + live-preview ajax (same renderer).
 * ========================================================================= */
add_filter('template_include', function ($template) {
    if (!is_page()) return $template;
    $pid = get_queried_object_id();
    if (!$pid || !get_post_meta($pid, '_ee_pb_on', true)) return $template;
    $t = locate_template('page-builder-canvas.php');
    return $t ?: $template;
}, 60);

function ee_pb_get_items($pid) {
    $items = get_post_meta($pid, '_ee_pb_json', true);
    return is_array($items) ? $items : array();
}

add_action('wp_ajax_ee_pb_preview', function () {
    if (!current_user_can('manage_options')) wp_die('', '', 403);
    check_ajax_referer('ee_pb_prev', 'nonce');
    $raw = json_decode(wp_unslash($_POST['pb_json'] ?? '[]'), true);
    echo ee_pb_render_page(ee_pb_sanitize_items($raw), true);
    wp_die();
});

/* =========================================================================
 * 5. Save / create / duplicate handlers.
 * ========================================================================= */
add_action('admin_post_ee_pb_save', function () {
    if (!current_user_can('manage_options')) wp_die('Not allowed');
    check_admin_referer('ee_pb_save');
    $pid = isset($_POST['pb_post']) ? (int) $_POST['pb_post'] : 0;
    if (!$pid || get_post_type($pid) !== 'page') wp_die('Bad page');
    $raw = json_decode(wp_unslash($_POST['pb_json'] ?? '[]'), true);
    update_post_meta($pid, '_ee_pb_json', ee_pb_sanitize_items($raw));
    update_post_meta($pid, '_ee_pb_on', empty($_POST['pb_on']) ? '' : '1');
    if (function_exists('ee_home_layout_flush_caches')) ee_home_layout_flush_caches();
    wp_safe_redirect(admin_url('admin.php?page=ee-page-builder&post=' . $pid . '&saved=1'));
    exit;
});

add_action('admin_post_ee_pb_new', function () {
    if (!current_user_can('manage_options')) wp_die('Not allowed');
    check_admin_referer('ee_pb_new');
    $title = sanitize_text_field(wp_unslash($_POST['pb_title'] ?? ''));
    if ($title === '') $title = 'New builder page';
    $pid = wp_insert_post(array('post_title' => $title, 'post_type' => 'page', 'post_status' => 'publish'));
    if (is_wp_error($pid) || !$pid) wp_die('Could not create page');
    update_post_meta($pid, '_ee_pb_on', '1');
    update_post_meta($pid, '_ee_pb_json', array());
    wp_safe_redirect(admin_url('admin.php?page=ee-page-builder&post=' . $pid));
    exit;
});

add_action('admin_post_ee_pb_duplicate', function () {
    if (!current_user_can('manage_options')) wp_die('Not allowed');
    check_admin_referer('ee_pb_duplicate');
    $src = isset($_GET['post']) ? (int) $_GET['post'] : 0;
    if (!$src || get_post_type($src) !== 'page') wp_die('Bad page');
    $pid = wp_insert_post(array(
        'post_title'  => get_the_title($src) . ' (copy)',
        'post_type'   => 'page',
        'post_status' => 'draft',
    ));
    if (is_wp_error($pid) || !$pid) wp_die('Could not duplicate');
    update_post_meta($pid, '_ee_pb_on', get_post_meta($src, '_ee_pb_on', true));
    update_post_meta($pid, '_ee_pb_json', ee_pb_get_items($src));
    wp_safe_redirect(admin_url('admin.php?page=ee-page-builder&post=' . $pid));
    exit;
});

/* =========================================================================
 * 6. Admin UI.
 * ========================================================================= */
add_action('admin_menu', function () {
    add_submenu_page('ee-site', 'Page Builder', '🏗️ Page Builder', 'manage_options', 'ee-page-builder', 'ee_pb_render_admin');
});

add_action('admin_enqueue_scripts', function ($hook) {
    if (strpos((string) $hook, 'ee-page-builder') !== false) wp_enqueue_media();
});

function ee_pb_render_admin() {
    if (!current_user_can('manage_options')) return;
    $pid = isset($_GET['post']) ? (int) $_GET['post'] : 0;
    if ($pid && get_post_type($pid) === 'page') { ee_pb_render_editor($pid); return; }
    ee_pb_render_list();
}

/** Screen 1 — pick a page (or create one). */
function ee_pb_render_list() {
    $pages = get_pages(array('sort_column' => 'post_title', 'number' => 300));
    ?>
    <div class="wrap" style="max-width:900px">
      <h1>🏗️ Page Builder</h1>
      <p style="font-size:14px;color:#50575e;max-width:74ch">Design pages visually — what you see in the editor is exactly what visitors get. Click any element on the canvas to edit it, type directly into the text, switch to mobile preview, undo with Ctrl+Z. Everything follows the site design automatically.</p>

      <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" style="background:#fff;border:1px solid #dcdcde;border-left:4px solid #DE6E30;border-radius:8px;padding:14px 18px;margin:16px 0;display:flex;gap:10px;align-items:center;max-width:660px">
        <?php wp_nonce_field('ee_pb_new'); ?>
        <input type="hidden" name="action" value="ee_pb_new">
        <b style="color:#19335D;white-space:nowrap">➕ New page:</b>
        <input type="text" name="pb_title" placeholder="Page title…" style="flex:1" required>
        <button class="button button-primary">Create &amp; open builder</button>
      </form>

      <table class="widefat striped" style="max-width:880px">
        <thead><tr><th>Page</th><th style="width:110px">Builder</th><th style="width:300px"></th></tr></thead>
        <tbody>
        <?php foreach ($pages as $p) : $on = get_post_meta($p->ID, '_ee_pb_on', true); ?>
          <tr>
            <td><b><?php echo esc_html($p->post_title ?: '(no title)'); ?></b><br><span style="color:#8a8f98;font-size:12px">/<?php echo esc_html($p->post_name); ?>/</span></td>
            <td><?php echo $on ? '<span style="color:#1a7f37;font-weight:700">● On</span>' : '<span style="color:#8a8f98">Off</span>'; ?></td>
            <td>
              <a class="button" href="<?php echo esc_url(admin_url('admin.php?page=ee-page-builder&post=' . $p->ID)); ?>">Edit with builder</a>
              <a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=ee_pb_duplicate&post=' . $p->ID), 'ee_pb_duplicate')); ?>">Duplicate</a>
              <a class="button" href="<?php echo esc_url(get_permalink($p->ID)); ?>" target="_blank" rel="noopener">View</a>
            </td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    </div>
    <?php
}

/** Starter templates (arrays of elements, defaults filled client-side). */
function ee_pb_templates() {
    return array(
        'landing' => array('🚀 Landing page', array(
            array('t' => 'hero', 's' => array()),
            array('t' => 'logos', 's' => array()),
            array('t' => 'features', 's' => array()),
            array('t' => 'textimg', 's' => array()),
            array('t' => 'stats', 's' => array('_bg' => 'soft')),
            array('t' => 'testimonial', 's' => array()),
            array('t' => 'faq', 's' => array()),
            array('t' => 'cta', 's' => array()),
        )),
        'product' => array('📦 Product page', array(
            array('t' => 'hero', 's' => array()),
            array('t' => 'textimg', 's' => array()),
            array('t' => 'textimg', 's' => array('image_pos' => 'left')),
            array('t' => 'features', 's' => array('_bg' => 'soft')),
            array('t' => 'video', 's' => array()),
            array('t' => 'pricing', 's' => array()),
            array('t' => 'cta', 's' => array()),
        )),
        'story' => array('💬 Story / Case study', array(
            array('t' => 'hero', 's' => array()),
            array('t' => 'stats', 's' => array()),
            array('t' => 'text', 's' => array()),
            array('t' => 'image', 's' => array()),
            array('t' => 'testimonial', 's' => array('_bg' => 'soft')),
            array('t' => 'cta', 's' => array()),
        )),
    );
}

/** Screen 2 — the visual builder. */
function ee_pb_render_editor($pid) {
    $reg   = ee_pb_elements();
    $items = ee_pb_get_items($pid);
    $on    = (bool) get_post_meta($pid, '_ee_pb_on', true);
    $schema = array();
    foreach ($reg as $t => $def) {
        $fields = array();
        foreach ($def[2] as $k => $f) {
            $fields[$k] = array('label' => $f[0], 'input' => $f[1], 'def' => $f[2], 'options' => isset($f[3]) ? $f[3] : null);
        }
        foreach (ee_pb_style_fields() as $k => $f) {
            $fields[$k] = array('label' => $f[0], 'input' => $f[1], 'def' => $f[2], 'options' => $f[3]);
        }
        $schema[$t] = array('label' => $def[0], 'icon' => $def[1], 'fields' => $fields);
    }
    $templates = array();
    foreach (ee_pb_templates() as $key => $tpl) { $templates[$key] = array('label' => $tpl[0], 'items' => $tpl[1]); }
    ?>
    <div class="wrap" style="max-width:none;margin-right:10px">
      <h1 style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">🏗️ <?php echo esc_html(get_the_title($pid)); ?>
        <a class="button" href="<?php echo esc_url(admin_url('admin.php?page=ee-page-builder')); ?>">← All pages</a>
        <a class="button" href="<?php echo esc_url(get_permalink($pid)); ?>" target="_blank" rel="noopener">👁 View live</a>
        <span style="flex:1"></span>
        <span class="eepb-dev">
          <button type="button" class="button dev on" data-w="100%">🖥 Desktop</button>
          <button type="button" class="button dev" data-w="768px">📲 Tablet</button>
          <button type="button" class="button dev" data-w="390px">📱 Mobile</button>
        </span>
        <button type="button" class="button" id="eepbUndo" title="Ctrl+Z">↩ Undo</button>
        <button type="button" class="button" id="eepbRedo" title="Ctrl+Shift+Z">↪ Redo</button>
      </h1>
      <?php if (!empty($_GET['saved'])) : ?><div class="notice notice-success is-dismissible"><p>Saved! The live page is updated (purge your site cache if you use one).</p></div><?php endif; ?>

      <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" id="eepbForm">
        <?php wp_nonce_field('ee_pb_save'); ?>
        <input type="hidden" name="action" value="ee_pb_save">
        <input type="hidden" name="pb_post" value="<?php echo (int) $pid; ?>">
        <input type="hidden" name="pb_json" id="eepbJson" value="">
        <p style="display:flex;gap:16px;align-items:center;flex-wrap:wrap">
          <label style="font-weight:600"><input type="checkbox" name="pb_on" value="1" <?php checked($on); ?>> Render this page with the builder</label>
          <button class="button button-primary button-large">💾 Save page</button>
          <button type="button" class="button" id="eepbExport">⬆ Copy layout</button>
          <button type="button" class="button" id="eepbImport">⬇ Paste layout</button>
        </p>

        <div class="eepb-admin">
          <div class="eepb-left">
            <div class="eepb-box">
              <h3>Elements</h3>
              <div id="eepbPal"></div>
            </div>
            <div class="eepb-box">
              <h3>Templates</h3>
              <div id="eepbTpl"></div>
              <p class="hint">One click inserts a full page skeleton — then click any text on the canvas and type.</p>
            </div>
          </div>

          <div class="eepb-mid">
            <div class="eepb-canvas-frame" id="eepbFrameWrap">
              <iframe id="eepbFrame" title="Live preview"></iframe>
            </div>
          </div>

          <div class="eepb-right">
            <div class="eepb-box">
              <h3>Layers</h3>
              <ul id="eepbLayers"></ul>
              <p class="hint" id="eepbEmpty">No elements yet — add from the left or pick a template.</p>
            </div>
            <div class="eepb-box">
              <h3>Settings</h3>
              <div id="eepbSettings"><p class="hint">Click an element on the canvas to edit it.</p></div>
            </div>
          </div>
        </div>
      </form>

      <style>
        .eepb-admin{display:grid;grid-template-columns:210px minmax(420px,1fr) 330px;gap:14px;align-items:start}
        .eepb-box{background:#fff;border:1px solid #dcdcde;border-radius:10px;padding:12px;margin-bottom:14px}
        .eepb-box h3{margin:0 0 10px;font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#50575e}
        #eepbPal button.pal,#eepbTpl button.pal{display:flex;align-items:center;gap:8px;width:100%;text-align:left;background:#f6f7f7;border:1px solid #dcdcde;border-radius:8px;padding:8px 10px;margin-bottom:6px;cursor:pointer;font-weight:600;color:#19335D;font-size:12.5px}
        #eepbPal button.pal:hover,#eepbTpl button.pal:hover{border-color:#DE6E30;background:#fff7f2}
        .eepb-canvas-frame{background:#e8ebf0;border:1px solid #dcdcde;border-radius:12px;padding:16px;display:flex;justify-content:center;min-height:70vh}
        #eepbFrame{width:100%;max-width:100%;height:calc(100vh - 220px);min-height:560px;border:0;background:#fff;border-radius:8px;box-shadow:0 10px 30px rgba(15,30,60,.12);transition:width .25s ease}
        .eepb-dev .dev.on{background:#19335D;color:#fff;border-color:#19335D}
        #eepbLayers{margin:0;min-height:30px}
        #eepbLayers li{display:flex;align-items:center;gap:8px;background:#f6f7f7;border:1px solid #dcdcde;border-radius:8px;padding:7px 9px;margin-bottom:6px;cursor:grab;font-size:12.5px}
        #eepbLayers li.sel{border-color:#DE6E30;background:#fff7f2;box-shadow:0 0 0 1px #DE6E30}
        #eepbLayers li.dragging{opacity:.45}
        #eepbLayers li .nm{font-weight:700;color:#19335D;flex:none}
        #eepbLayers li .sum{color:#8a8f98;font-size:11.5px;flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
        #eepbLayers li .ops{display:flex;gap:2px;flex:none}
        #eepbLayers li .ops button{border:0;background:none;cursor:pointer;font-size:13px;padding:1px 3px;color:#50575e}
        #eepbLayers li .ops button:hover{color:#DE6E30}
        .eepb-right label{display:block;font-weight:600;font-size:12.5px;color:#19335D;margin:11px 0 4px}
        .eepb-right input[type=text],.eepb-right input[type=url],.eepb-right input[type=number],.eepb-right select,.eepb-right textarea{width:100%}
        .eepb-right textarea{min-height:100px;font-family:Menlo,Consolas,monospace;font-size:12px}
        .eepb-right .imgpick{display:flex;gap:6px}
        .eepb-right .imgpick input{flex:1}
        .eepb-insp-row{display:flex;gap:6px;align-items:center}
        .eepb-insp-row input[type=color]{width:52px;height:32px;padding:2px;flex:none}
        .eepb-insp-row input[type=number],.eepb-insp-row input[type=text]{flex:1;min-width:0}
        .eepb-insp-row select{flex:1;min-width:0}
        .eepb-act{display:flex;flex-wrap:wrap;gap:6px;margin-top:14px}
        .hint{color:#8a8f98;font-size:12px}
        @media(max-width:1280px){.eepb-admin{grid-template-columns:190px 1fr 300px}}
      </style>

      <script>
      (function(){
        var SCHEMA = <?php echo wp_json_encode($schema); ?>;
        var TPL    = <?php echo wp_json_encode($templates); ?>;
        var state  = <?php echo wp_json_encode(array_values($items)); ?>;
        var AJAX   = <?php echo wp_json_encode(admin_url('admin-ajax.php')); ?>;
        var NONCE  = <?php echo wp_json_encode(wp_create_nonce('ee_pb_prev')); ?>;
        var sel = -1, editing = false, prevT = null;
        var undoStack = [], redoStack = [];

        var pal = document.getElementById('eepbPal'),
            tplBox = document.getElementById('eepbTpl'),
            layers = document.getElementById('eepbLayers'),
            settings = document.getElementById('eepbSettings'),
            empty = document.getElementById('eepbEmpty'),
            jsonInp = document.getElementById('eepbJson'),
            frame = document.getElementById('eepbFrame');

        function defaults(t){
          var s = {};
          Object.keys(SCHEMA[t].fields).forEach(function(k){ s[k] = SCHEMA[t].fields[k].def; });
          return s;
        }
        function snapshot(){
          undoStack.push(JSON.stringify(state));
          if (undoStack.length > 60) undoStack.shift();
          redoStack.length = 0;
        }
        function restore(str){
          editing = false;
          state = JSON.parse(str);
          if (sel >= state.length) sel = state.length - 1;
          sync(); drawLayers(); drawSettings(); preview();
        }
        function undo(){ if (!undoStack.length) return; redoStack.push(JSON.stringify(state)); restore(undoStack.pop()); }
        function redo(){ if (!redoStack.length) return; undoStack.push(JSON.stringify(state)); restore(redoStack.pop()); }
        document.getElementById('eepbUndo').addEventListener('click', undo);
        document.getElementById('eepbRedo').addEventListener('click', redo);
        document.addEventListener('keydown', function(e){
          if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? redo() : undo(); }
        });

        function sync(){ jsonInp.value = JSON.stringify(state); }

        /* ---- palette + templates ---- */
        Object.keys(SCHEMA).forEach(function(t){
          var b = document.createElement('button');
          b.type = 'button'; b.className = 'pal';
          b.innerHTML = '<span>' + SCHEMA[t].icon + '</span> ' + SCHEMA[t].label;
          b.addEventListener('click', function(){
            editing = false; snapshot();
            state.push({t: t, s: defaults(t)});
            sel = state.length - 1;
            sync(); drawLayers(); drawSettings(); preview();
          });
          pal.appendChild(b);
        });
        Object.keys(TPL).forEach(function(k){
          var b = document.createElement('button');
          b.type = 'button'; b.className = 'pal';
          b.textContent = TPL[k].label;
          b.addEventListener('click', function(){
            editing = false; snapshot();
            TPL[k].items.forEach(function(it){
              var s = defaults(it.t);
              Object.keys(it.s || {}).forEach(function(kk){ s[kk] = it.s[kk]; });
              state.push({t: it.t, s: s});
            });
            sel = state.length - 1;
            sync(); drawLayers(); drawSettings(); preview();
          });
          tplBox.appendChild(b);
        });

        /* ---- layers column ---- */
        function summary(it){
          var s = it.s || {};
          if (it.t === 'html') return s.code ? 'pasted page (' + Math.round(String(s.code).length / 1024) + ' KB)' : '(empty — paste HTML)';
          return s.heading || s.text || s.content || s.quote || s.section || s.items || '';
        }
        function drawLayers(){
          layers.innerHTML = '';
          empty.style.display = state.length ? 'none' : '';
          state.forEach(function(it, i){
            var li = document.createElement('li');
            li.draggable = true; li.dataset.i = i;
            if (i === sel) li.className = 'sel';
            li.innerHTML = '<span>' + (SCHEMA[it.t] ? SCHEMA[it.t].icon : '❔') + '</span>'
              + '<span class="nm">' + (SCHEMA[it.t] ? SCHEMA[it.t].label : it.t) + '</span>'
              + '<span class="sum"></span>'
              + '<span class="ops">'
              + '<button type="button" data-op="up" title="Move up">▲</button>'
              + '<button type="button" data-op="down" title="Move down">▼</button>'
              + '<button type="button" data-op="dup" title="Duplicate">⧉</button>'
              + '<button type="button" data-op="del" title="Delete">✕</button>'
              + '</span>';
            li.querySelector('.sum').textContent = String(summary(it)).slice(0, 40);
            layers.appendChild(li);
          });
        }
        layers.addEventListener('click', function(e){
          editing = false;                    /* leaving canvas typing mode */
          var li = e.target.closest('li'); if (!li) return;
          var i = parseInt(li.dataset.i, 10);
          var opBtn = e.target.closest('button');
          var op = opBtn ? opBtn.dataset.op : null;
          if (op) snapshot();
          if (op === 'del') { state.splice(i, 1); if (sel >= state.length) sel = state.length - 1; }
          else if (op === 'dup') { state.splice(i + 1, 0, JSON.parse(JSON.stringify(state[i]))); sel = i + 1; }
          else if (op === 'up' && i > 0) { var a = state.splice(i, 1)[0]; state.splice(i - 1, 0, a); sel = i - 1; }
          else if (op === 'down' && i < state.length - 1) { var b2 = state.splice(i, 1)[0]; state.splice(i + 1, 0, b2); sel = i + 1; }
          else { sel = i; drawLayers(); drawSettings(); mark(); return; }
          sync(); drawLayers(); drawSettings(); preview();
        });
        var dragI = null;
        layers.addEventListener('dragstart', function(e){
          var li = e.target.closest('li'); if (!li) return;
          dragI = parseInt(li.dataset.i, 10); li.classList.add('dragging'); snapshot();
        });
        layers.addEventListener('dragend', function(){ dragI = null; sync(); drawLayers(); preview(); });
        layers.addEventListener('dragover', function(e){
          e.preventDefault();
          var li = e.target.closest('li'); if (!li || dragI === null) return;
          var i = parseInt(li.dataset.i, 10);
          if (i === dragI) return;
          var m = state.splice(dragI, 1)[0];
          state.splice(i, 0, m);
          sel = i; dragI = i;
          drawLayers();
          var rows = layers.querySelectorAll('li');
          if (rows[i]) rows[i].classList.add('dragging');
        });

        /* Interacting with the panel means canvas typing is over — without
           this, a missed iframe blur leaves `editing` stuck and the live
           preview stops refreshing. */
        settings.addEventListener('focusin', function(){ editing = false; });
        settings.addEventListener('mousedown', function(){ editing = false; });

        /* =================================================================
         * Inspector for pasted-HTML blocks: click ANY element inside the
         * pasted page to restyle it (colors, font, size, image, link,
         * spacing) or duplicate/hide/delete it — all changes serialize
         * straight back into the stored HTML.
         * ================================================================= */
        var inSel = null;   /* {el, nd, nf, i} — the selected inner element */

        function saveHtml(i, nd){
          try {
            var clone = nd.documentElement.cloneNode(true);
            var fx = clone.querySelector('#__eepb_pv_fix'); if (fx) fx.remove();
            var rs = clone.querySelector('#__eepb_rescue'); if (rs) rs.remove();
            clone.querySelectorAll('[contenteditable]').forEach(function(el){ el.removeAttribute('contenteditable'); el.removeAttribute('spellcheck'); });
            clone.querySelectorAll('.__eepb_sel, .__eepb_hov').forEach(function(el){
              el.classList.remove('__eepb_sel', '__eepb_hov');
              if (!el.getAttribute('class')) el.removeAttribute('class');
            });
            if (state[i]) {
              state[i].s.code = '<!DOCTYPE html>\n' + clone.outerHTML;
              sync();
              var row = layers.querySelector('li[data-i="' + i + '"] .sum');
              if (row) row.textContent = String(summary(state[i])).slice(0, 40);
            }
          } catch (e) {}
        }
        function refit(nf){
          try {
            var nd = nf.contentDocument; if (!nd || !nd.body) return;
            var h = Math.max(nd.documentElement.getBoundingClientRect().height, nd.body.getBoundingClientRect().height, nd.documentElement.scrollHeight);
            nf.style.height = Math.max(320, Math.min(Math.ceil(h) + 4, 20000)) + 'px';
          } catch (e) {}
        }
        function rgb2hex(c){
          var m = /rgba?\((\d+),\s*(\d+),\s*(\d+)/.exec(c || '');
          if (!m) return '#000000';
          return '#' + [m[1], m[2], m[3]].map(function(n){ return ('0' + parseInt(n, 10).toString(16)).slice(-2); }).join('');
        }
        function elPath(el){
          var parts = [], n = el, hops = 0;
          while (n && n.tagName && n.tagName !== 'BODY' && hops < 3) { parts.unshift(n.tagName.toLowerCase()); n = n.parentElement; hops++; }
          return parts.join(' › ') || el.tagName.toLowerCase();
        }
        function clearInSel(){
          if (inSel && inSel.el && inSel.el.classList) inSel.el.classList.remove('__eepb_sel');
          inSel = null;
        }

        function drawInspector(){
          if (!inSel || !inSel.el || !inSel.el.isConnected) { clearInSel(); drawSettings(); return; }
          var el = inSel.el, nd = inSel.nd, nf = inSel.nf, i = inSel.i;
          var tag = el.tagName.toLowerCase();
          var snapped = false;
          function snapOnce(){ if (!snapped) { snapped = true; snapshot(); } }
          function save(){ saveHtml(i, nd); refit(nf); }
          function lab(t){ var l = document.createElement('label'); l.textContent = t; settings.appendChild(l); return l; }

          settings.innerHTML = '';
          var head = document.createElement('p');
          head.innerHTML = '<b>🎯 ' + elPath(el) + '</b><br><span class="hint">Type directly on the page to change text. Style it below.</span>';
          settings.appendChild(head);

          /* --- colors --- */
          function colorCtl(label, prop){
            lab(label);
            var row = document.createElement('div'); row.className = 'eepb-insp-row';
            var c = document.createElement('input'); c.type = 'color';
            c.value = rgb2hex(getComputedStyle(el)[prop === 'background' ? 'backgroundColor' : prop]);
            c.addEventListener('mousedown', snapOnce); c.addEventListener('focus', snapOnce);
            c.addEventListener('input', function(){ el.style[prop] = c.value; save(); });
            var x = document.createElement('button'); x.type = 'button'; x.className = 'button'; x.textContent = '✕'; x.title = 'Remove this color (back to original)';
            x.addEventListener('click', function(){ snapOnce(); el.style[prop] = ''; save(); });
            row.appendChild(c); row.appendChild(x); settings.appendChild(row);
          }
          colorCtl('Text color', 'color');
          colorCtl('Background color', 'background');

          /* --- font --- */
          lab('Font');
          var fsel = document.createElement('select');
          [['', 'Original (as designed)'], ["'Inter',sans-serif", 'Inter (site font)'], ['Arial,Helvetica,sans-serif', 'Arial'], ['Georgia,serif', 'Georgia'], ["'Times New Roman',serif", 'Times New Roman'], ['Verdana,sans-serif', 'Verdana'], ["'Trebuchet MS',sans-serif", 'Trebuchet MS'], ["'Courier New',monospace", 'Courier New'], ['system-ui,sans-serif', 'System UI']].forEach(function(o){
            var op = document.createElement('option'); op.value = o[0]; op.textContent = o[1]; fsel.appendChild(op);
          });
          fsel.value = el.style.fontFamily || '';
          fsel.addEventListener('mousedown', snapOnce);
          fsel.addEventListener('change', function(){
            snapOnce();
            el.style.fontFamily = fsel.value;
            if (fsel.value.indexOf('Inter') !== -1 && !nd.getElementById('__eepb_inter')) {
              var lk = nd.createElement('link'); lk.id = '__eepb_inter'; lk.rel = 'stylesheet';
              lk.href = 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap';
              (nd.head || nd.body).appendChild(lk);   /* kept in the saved page on purpose */
            }
            save();
          });
          settings.appendChild(fsel);

          /* --- size / weight / align --- */
          lab('Font size (px) — leave empty for original');
          var fs = document.createElement('input'); fs.type = 'number'; fs.min = '8'; fs.max = '120';
          fs.value = el.style.fontSize ? parseInt(el.style.fontSize, 10) : '';
          fs.placeholder = parseInt(getComputedStyle(el).fontSize, 10);
          fs.addEventListener('focus', snapOnce);
          fs.addEventListener('input', function(){ el.style.fontSize = fs.value ? fs.value + 'px' : ''; save(); });
          settings.appendChild(fs);

          lab('Weight & alignment');
          var row2 = document.createElement('div'); row2.className = 'eepb-insp-row';
          var w = document.createElement('select');
          [['', 'Weight'], ['400', 'Normal'], ['600', 'Semi-bold'], ['700', 'Bold'], ['800', 'Extra-bold']].forEach(function(o){
            var op = document.createElement('option'); op.value = o[0]; op.textContent = o[1]; w.appendChild(op);
          });
          w.value = el.style.fontWeight || '';
          w.addEventListener('mousedown', snapOnce);
          w.addEventListener('change', function(){ el.style.fontWeight = w.value; save(); });
          row2.appendChild(w);
          [['left', '⬅'], ['center', '↔'], ['right', '➡']].forEach(function(a){
            var btn = document.createElement('button'); btn.type = 'button'; btn.className = 'button'; btn.textContent = a[1]; btn.title = 'Align ' + a[0];
            btn.addEventListener('click', function(){ snapOnce(); el.style.textAlign = a[0]; save(); });
            row2.appendChild(btn);
          });
          settings.appendChild(row2);

          /* --- spacing --- */
          lab('Inside spacing / rounded corners (px)');
          var row3 = document.createElement('div'); row3.className = 'eepb-insp-row';
          var pad = document.createElement('input'); pad.type = 'number'; pad.min = '0'; pad.max = '200'; pad.placeholder = 'padding';
          pad.value = el.style.padding ? parseInt(el.style.padding, 10) : '';
          pad.addEventListener('focus', snapOnce);
          pad.addEventListener('input', function(){ el.style.padding = pad.value ? pad.value + 'px' : ''; save(); });
          var rad = document.createElement('input'); rad.type = 'number'; rad.min = '0'; rad.max = '80'; rad.placeholder = 'corners';
          rad.value = el.style.borderRadius ? parseInt(el.style.borderRadius, 10) : '';
          rad.addEventListener('focus', snapOnce);
          rad.addEventListener('input', function(){ el.style.borderRadius = rad.value ? rad.value + 'px' : ''; save(); });
          row3.appendChild(pad); row3.appendChild(rad); settings.appendChild(row3);

          /* --- image / logo --- */
          if (tag === 'img') {
            lab('Image / logo URL');
            var row4 = document.createElement('div'); row4.className = 'eepb-insp-row';
            var src = document.createElement('input'); src.type = 'text'; src.value = el.getAttribute('src') || '';
            src.addEventListener('focus', snapOnce);
            src.addEventListener('input', function(){ el.setAttribute('src', src.value); save(); });
            row4.appendChild(src);
            if (window.wp && wp.media) {
              var pk = document.createElement('button'); pk.type = 'button'; pk.className = 'button'; pk.textContent = '📁';
              pk.addEventListener('click', function(){
                var mfr = wp.media({title: 'Choose image', multiple: false, library: {type: 'image'}});
                mfr.on('select', function(){
                  snapOnce();
                  var att = mfr.state().get('selection').first().toJSON();
                  src.value = att.url; el.setAttribute('src', att.url); save();
                });
                mfr.open();
              });
              row4.appendChild(pk);
            }
            settings.appendChild(row4);
            lab('Alt text (SEO)');
            var alt = document.createElement('input'); alt.type = 'text'; alt.value = el.getAttribute('alt') || '';
            alt.addEventListener('focus', snapOnce);
            alt.addEventListener('input', function(){ el.setAttribute('alt', alt.value); save(); });
            settings.appendChild(alt);
            lab('Image width (%) — empty for original');
            var iw = document.createElement('input'); iw.type = 'number'; iw.min = '5'; iw.max = '100';
            iw.value = el.style.width && el.style.width.indexOf('%') !== -1 ? parseInt(el.style.width, 10) : '';
            iw.addEventListener('focus', snapOnce);
            iw.addEventListener('input', function(){ el.style.width = iw.value ? iw.value + '%' : ''; save(); });
            settings.appendChild(iw);
          }

          /* --- link --- */
          var aEl = (tag === 'a') ? el : (el.closest ? el.closest('a') : null);
          if (aEl) {
            lab('Link URL (button / link target)');
            var href = document.createElement('input'); href.type = 'text'; href.value = aEl.getAttribute('href') || '';
            href.addEventListener('focus', snapOnce);
            href.addEventListener('input', function(){ aEl.setAttribute('href', href.value); save(); });
            settings.appendChild(href);
          }

          /* --- actions --- */
          var act = document.createElement('div'); act.className = 'eepb-act';
          function actBtn(txt, title, fn){
            var btn = document.createElement('button'); btn.type = 'button'; btn.className = 'button'; btn.textContent = txt; btn.title = title;
            btn.addEventListener('click', fn); act.appendChild(btn);
          }
          actBtn('⬆ Select parent', 'Select the section around this element', function(){
            var p = el.parentElement;
            if (!p || p === nd.documentElement) return;
            el.classList.remove('__eepb_sel');
            inSel.el = p;
            p.classList.add('__eepb_sel');
            drawInspector();
          });
          actBtn('⧉ Duplicate', 'Duplicate this element/section', function(){
            snapshot();
            var c = el.cloneNode(true);
            c.classList.remove('__eepb_sel', '__eepb_hov');
            el.after(c); save();
          });
          actBtn(el.style.display === 'none' ? '👁 Show' : '🙈 Hide', 'Hide/show (undo with Ctrl+Z)', function(){
            snapshot();
            el.style.display = (el.style.display === 'none') ? '' : 'none';
            save(); drawInspector();
          });
          actBtn('🗑 Delete', 'Delete this element/section (undo with Ctrl+Z)', function(){
            snapshot();
            el.remove(); save();
            clearInSel(); drawSettings();
          });
          actBtn('{ } Code', 'Show the raw HTML of this whole block', function(){
            clearInSel(); drawSettings();
          });
          settings.appendChild(act);
        }

        /* ---- settings panel ---- */
        function drawSettings(){
          settings.innerHTML = '';
          if (sel < 0 || !state[sel]) { settings.innerHTML = '<p class="hint">Click an element on the canvas to edit it.</p>'; return; }
          var it = state[sel], sch = SCHEMA[it.t];
          if (!sch) return;
          var head = document.createElement('p');
          head.innerHTML = '<b>' + sch.icon + ' ' + sch.label + '</b>';
          settings.appendChild(head);
          Object.keys(sch.fields).forEach(function(k){
            var f = sch.fields[k];
            var lab = document.createElement('label');
            lab.textContent = f.label;
            settings.appendChild(lab);
            var inp, wrap = null;
            if (f.input === 'code') { inp = document.createElement('textarea'); inp.style.minHeight = '260px'; inp.placeholder = '<!DOCTYPE html> … paste the whole file here'; }
            else if (f.input === 'textarea') { inp = document.createElement('textarea'); }
            else if (f.input === 'select') {
              inp = document.createElement('select');
              Object.keys(f.options || {}).forEach(function(ov){
                var op = document.createElement('option');
                op.value = ov; op.textContent = f.options[ov];
                inp.appendChild(op);
              });
            }
            else if (f.input === 'check') { inp = document.createElement('input'); inp.type = 'checkbox'; }
            else { inp = document.createElement('input'); inp.type = (f.input === 'number' ? 'number' : 'text'); }
            if (f.input === 'check') { inp.checked = !!it.s[k]; }
            else { inp.value = (it.s[k] !== undefined ? it.s[k] : f.def); }
            inp.addEventListener('focus', function(){ snapshot(); });
            inp.addEventListener('input', function(){
              editing = false;              /* settings edit = not typing on canvas */
              it.s[k] = (f.input === 'check') ? (inp.checked ? '1' : '') : inp.value;
              sync();
              var row = layers.querySelector('li[data-i="' + sel + '"] .sum');
              if (row) row.textContent = String(summary(it)).slice(0, 40);
              preview();
            });
            if (f.input === 'url' && window.wp && wp.media) {
              wrap = document.createElement('div'); wrap.className = 'imgpick';
              var pick = document.createElement('button');
              pick.type = 'button'; pick.className = 'button'; pick.textContent = '📁';
              pick.title = 'Choose from Media Library';
              pick.addEventListener('click', function(){
                var fr2 = wp.media({title: 'Choose image', multiple: false, library: {type: 'image'}});
                fr2.on('select', function(){
                  var att = fr2.state().get('selection').first().toJSON();
                  inp.value = att.url;
                  inp.dispatchEvent(new Event('input'));
                });
                fr2.open();
              });
              wrap.appendChild(inp); wrap.appendChild(pick);
              settings.appendChild(wrap);
            } else {
              settings.appendChild(inp);
            }
          });
        }

        /* ---- live WYSIWYG preview (rendered by the same PHP as the site) ---- */
        function preview(){
          if (editing) return;                       /* don't yank the caret */
          clearTimeout(prevT);
          prevT = setTimeout(function(){
            var fd = new FormData();
            fd.append('action', 'ee_pb_preview');
            fd.append('nonce', NONCE);
            fd.append('pb_json', JSON.stringify(state));
            fetch(AJAX, {method: 'POST', credentials: 'same-origin', body: fd})
              .then(function(r){ return r.text(); })
              .then(function(html){
                frame.srcdoc = '<!DOCTYPE html><html><head><meta charset="utf-8">'
                  + '<meta name="viewport" content="width=device-width, initial-scale=1">'
                  + '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">'
                  + '<style>body{margin:0}'
                  + '.pbp-chip{position:sticky;top:0;z-index:50;background:#19335D;color:#fff;font:600 11.5px/1.4 Inter,sans-serif;padding:6px 12px;letter-spacing:.02em}'
                  + '.pbp-item{position:relative;cursor:pointer}'
                  + '.pbp-item:hover{outline:2px dashed rgba(222,110,48,.6);outline-offset:-2px}'
                  + '.pbp-item.on{outline:2px solid #DE6E30;outline-offset:-2px}'
                  + '[data-edit]{outline:none;border-radius:3px}'
                  + '[data-edit]:hover{box-shadow:0 0 0 1px rgba(222,110,48,.5)}'
                  + '[data-edit]:focus{box-shadow:0 0 0 2px #DE6E30;background:rgba(222,110,48,.05)}'
                  + '</style></head><body>' + html + '</body></html>';
              });
          }, 320);
        }

        function mark(){
          try {
            var d = frame.contentDocument; if (!d) return;
            d.querySelectorAll('.pbp-item').forEach(function(el){
              el.classList.toggle('on', parseInt(el.dataset.i, 10) === sel);
            });
          } catch (e) {}
        }

        frame.addEventListener('load', function(){
          try {
            var d = frame.contentDocument; if (!d) return;
            /* click an element on the canvas -> select it */
            d.addEventListener('click', function(e){
              var item = e.target.closest('.pbp-item');
              if (e.target.closest('a')) e.preventDefault();
              if (!item) return;
              clearInSel();                     /* leaving the HTML inspector */
              sel = parseInt(item.dataset.i, 10);
              drawLayers(); drawSettings(); mark();
            });
            /* type directly into the page */
            d.querySelectorAll('[data-edit]').forEach(function(el){
              el.setAttribute('contenteditable', 'true');
              el.setAttribute('spellcheck', 'false');
              el.addEventListener('focus', function(){ editing = true; snapshot(); });
              el.addEventListener('input', function(){
                var item = el.closest('.pbp-item'); if (!item) return;
                var i = parseInt(item.dataset.i, 10), k = el.getAttribute('data-edit');
                if (state[i]) { state[i].s[k] = el.textContent; sync();
                  var row = layers.querySelector('li[data-i="' + i + '"] .sum');
                  if (row) row.textContent = String(summary(state[i])).slice(0, 40);
                  if (i === sel) {
                    var inps = settings.querySelectorAll('input,textarea,select');
                    /* refresh matching settings input without re-rendering */
                    inps.forEach(function(inp){ /* labels precede inputs in DOM order; cheap sync on blur instead */ });
                  }
                }
              });
              el.addEventListener('blur', function(){
                editing = false;
                drawSettings(); preview();
              });
            });
            /* pasted-HTML blocks: fit height, inline text editing AND the
               click-anything inspector (colors, fonts, images, links,
               spacing, duplicate/hide/delete) */
            d.querySelectorAll('iframe.eepb-htmlpv').forEach(function(nf){
              var item = nf.closest('.pbp-item');
              var idx = item ? parseInt(item.dataset.i, 10) : -1;
              function wire2(){
                try {
                  var nd = nf.contentDocument; if (!nd || !nd.body || idx < 0) return;
                  refit(nf);
                  nd.body.setAttribute('contenteditable', 'true');
                  nd.body.setAttribute('spellcheck', 'false');
                  var snapped = false;
                  nd.addEventListener('focusin', function(){ editing = true; if (!snapped) { snapped = true; snapshot(); } });
                  nd.addEventListener('input', function(){ saveHtml(idx, nd); });
                  nd.addEventListener('focusout', function(){ editing = false; snapped = false; });
                  /* hover outline + click-to-inspect */
                  nd.addEventListener('mouseover', function(e){
                    var t = e.target;
                    if (!t || !t.classList || t === nd.body || t === nd.documentElement) return;
                    t.classList.add('__eepb_hov');
                  });
                  nd.addEventListener('mouseout', function(e){
                    if (e.target && e.target.classList) e.target.classList.remove('__eepb_hov');
                  });
                  nd.addEventListener('click', function(e){
                    var t = e.target;
                    if (t && t.closest && t.closest('a')) e.preventDefault();
                    if (!t || !t.classList || t === nd.documentElement) return;
                    if (t === nd.body) return;
                    clearInSel();
                    t.classList.remove('__eepb_hov');
                    inSel = { el: t, nd: nd, nf: nf, i: idx };
                    t.classList.add('__eepb_sel');
                    sel = idx;
                    drawLayers();
                    drawInspector();
                  }, true);
                } catch (e) {}
              }
              if (nf.contentDocument && nf.contentDocument.readyState === 'complete') { wire2(); }
              nf.addEventListener('load', wire2);
            });
            mark();
          } catch (e) {}
        });

        /* ---- device preview ---- */
        document.querySelectorAll('.eepb-dev .dev').forEach(function(b){
          b.addEventListener('click', function(){
            document.querySelectorAll('.eepb-dev .dev').forEach(function(x){ x.classList.remove('on'); });
            b.classList.add('on');
            frame.style.width = b.dataset.w;
          });
        });

        /* ---- export / import ---- */
        document.getElementById('eepbExport').addEventListener('click', function(){
          var txt = JSON.stringify(state);
          if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(txt).then(function(){ alert('Layout copied! Paste it into another page with "Paste layout".'); });
          } else { window.prompt('Copy this layout JSON:', txt); }
        });
        document.getElementById('eepbImport').addEventListener('click', function(){
          var txt = window.prompt('Paste a layout JSON here (it will be ADDED after the current elements):');
          if (!txt) return;
          try {
            var arr = JSON.parse(txt);
            if (!Array.isArray(arr)) throw new Error('not a layout');
            snapshot();
            arr.forEach(function(it){ if (it && it.t && SCHEMA[it.t]) state.push({t: it.t, s: it.s || defaults(it.t)}); });
            sync(); drawLayers(); drawSettings(); preview();
          } catch (e) { alert('That does not look like a layout JSON.'); }
        });

        document.getElementById('eepbForm').addEventListener('submit', function(){ sync(); });

        /* boot */
        sync(); drawLayers(); drawSettings(); preview();
      })();
      </script>
    </div>
    <?php
}
