<?php
/**
 * Site pages registry — every standalone marketing/landing page that is not
 * a CPT entry, keyed by its URL path. page-sitepage.php renders whatever is
 * here; the router in functions.php claims a path only when WordPress found
 * nothing else there (a real Page/CPT post published later always wins).
 *
 * Each entry:
 *   'g'   group key (drives steps/stats defaults + related-pages strip)
 *   't'   short name (breadcrumb, <title>, related chips)
 *   'h1'  page headline    'sub' one-para promise under it
 *   'f'   six "Title|One line" feature cards
 * Optional overrides: 'steps', 'stats', 'cta'.
 *
 * @package ExtraaEdge
 */
if (!defined('ABSPATH')) exit;

function ee_site_page_groups() {
    return array(
        'automation' => array(
            'label' => 'Automation',
            'steps' => array(
                'Map your funnel|Stages, sources, courses and teams - modelled in an afternoon with our team.',
                'Switch the rules on|Start from proven admission playbooks and tune them to your process.',
                'Watch it run|Every lead moves on time while your team only handles conversations.',
            ),
            'stats' => array('30 sec|Avg. first response', '40%|Higher conversions', '0|Leads slipping through', '24x7|Always working'),
            'cta'   => 'See automation on your own funnel',
        ),
        'security' => array(
            'label' => 'Security & Trust',
            'steps' => array(
                'Define who does what|Roles and permissions mapped to your org in minutes.',
                'Everything is recorded|Every view, edit and export lands in the audit trail.',
                'Stay audit-ready|Certifications, residency and retention handled by the platform.',
            ),
            'stats' => array('ISO 27001|Certified', 'GDPR|Ready', '100%|Actions audited', 'India|Data residency'),
            'cta'   => 'Talk to us about security & compliance',
        ),
        'analytics' => array(
            'label' => 'Analytics',
            'steps' => array(
                'Connect your funnel|Every enquiry, call, message and payment feeds one model.',
                'Open your dashboard|Live numbers by course, source, counsellor and campus.',
                'Act on what you see|Drill from any number to the exact leads behind it.',
            ),
            'stats' => array('1|Source of truth', 'Live|Not last week\'s export', '6.5x|ROI visibility', '50+|Ready reports'),
            'cta'   => 'See your numbers in one dashboard',
        ),
        'teams' => array(
            'label' => 'Solutions by Team',
            'steps' => array(
                'Bring the team on|Roles, views and targets set up for how your team works.',
                'Work one queue|Everyone sees exactly what needs them next - nothing else.',
                'Measure what matters|Live scoreboards per person, course and campaign.',
            ),
            'stats' => array('500+|Institutions onboard', '40%|More output per person', '7 days|To go live', '24x7|AI support'),
            'cta'   => 'Book a demo for your team',
        ),
        'usecase' => array(
            'label' => 'Solutions by Use Case',
            'steps' => array(
                'Plug in your sources|Ads, forms, portals, walk-ins and calls - captured automatically.',
                'Let AI do the first mile|Instant replies, qualification and routing on every enquiry.',
                'Convert with focus|Counsellors spend their day only on ready-to-enrol students.',
            ),
            'stats' => array('10M+|Enquiries managed', '30 sec|First response', '98%|WhatsApp open rate', '2x|More conversions'),
            'cta'   => 'See this working on sample data',
        ),
        'outcome' => array(
            'label' => 'Solutions by Outcome',
            'steps' => array(
                'Baseline your funnel|We measure response time, conversion and cost per enrolment today.',
                'Fix the leaks|AI responds first, follows up always and prioritises best-fit students.',
                'Compound the gains|Every cycle starts from a cleaner, faster, smarter funnel.',
            ),
            'stats' => array('37%|Higher conversions', '12x|Faster response', '46%|Lower cost/enrol', '4.2 Cr|Revenue influenced'),
            'cta'   => 'Get this outcome for your institution',
        ),
        'communication' => array(
            'label' => 'Communication',
            'steps' => array(
                'Connect your channels|Chatbot, WhatsApp, calling, email and SMS - live in days.',
                'Let AI answer first|Every enquiry gets an instant, accurate reply 24x7.',
                'Converse from the CRM|Every message logged on the student, whoever sent it.',
            ),
            'stats' => array('98%|WhatsApp open rate', '30 sec|First response', '95+|Languages', '24x7|Always on'),
            'cta'   => 'See every channel working together',
        ),
        'abroad' => array(
            'label' => 'Study Abroad',
            'steps' => array(
                'Model your pipelines|Countries, courses, intakes and agents - structured in days.',
                'Automate the journey|Documents, applications and follow-ups chased by the platform.',
                'Grow with visibility|Every agent, branch and intake measured honestly.',
            ),
            'stats' => array('15+|Countries served', '30 sec|First response', '100%|Agent visibility', '24x7|AI support'),
            'cta'   => 'Book a demo for your study-abroad business',
        ),
        'institution' => array(
            'label' => 'Industries',
            'steps' => array(
                'Tuned to your motion|Stages, sources and journeys set up for how your segment recruits.',
                'AI on every enquiry|Instant answers, calling and follow-ups from day one.',
                'Measured every cycle|Seats, sources and counsellors on live dashboards.',
            ),
            'stats' => array('500+|Institutions onboard', '7 days|To go live', '37%|Higher conversions', '24x7|AI support'),
            'cta'   => 'See it tuned to your institution',
        ),
        'proof' => array(
            'label' => 'Customer Proof',
            'steps' => null,
            'stats' => array('500+|Institutions', '15+|Countries', '10M+|Enquiries managed', '4.6/5|Avg. rating'),
            'cta'   => 'Join 500+ winning institutions',
        ),
        'resources' => array(
            'label' => 'Resources',
            'steps' => null,
            'stats' => array('500+|Institutions helped', '50+|Integrations', '99.9%|Uptime', '24x7|Support'),
            'cta'   => 'Have a question? Talk to us',
        ),
        'company' => array(
            'label' => 'Company',
            'steps' => null,
            'stats' => array('2015|Founded', '500+|Customers', '15+|Countries', '100+|Team members'),
            'cta'   => 'Come talk to us',
        ),
    );
}

function ee_site_pages() {
    return array(

    /* ── AUTOMATION (products/*) ─────────────────────────────────────── */
    'products/workflow-automation' => array('g' => 'automation', 't' => 'Workflow Automation',
        'h1' => 'Admissions That Run Themselves',
        'sub' => 'No-code rules that assign, nurture, escalate and notify - every lead moves the moment it should, without anyone having to remember.',
        'f' => array(
            'If-this-then-that builder|Compose rules in plain language - no developers, no scripts.',
            'Auto-assign instantly|New enquiries land with the right counsellor by course, city or source.',
            'Stage-based nurturing|Email, SMS and WhatsApp fire automatically as a lead moves.',
            'Stall escalation|A lead stuck in a stage too long is flagged and reassigned.',
            'Office-hours aware|Rules respect shifts, holidays and counsellor capacity.',
            'Readable automation|Open any rule and see exactly why a lead moved - no black box.',
        )),
    'products/journey-builder' => array('g' => 'automation', 't' => 'Journey Builder',
        'h1' => 'Design the Student Journey Visually',
        'sub' => 'Drag every touchpoint - from first enquiry to fee payment - onto one canvas, and let the platform walk each student through it.',
        'f' => array(
            'Visual canvas|See the whole journey - branches, waits and messages - on one screen.',
            'Multi-channel steps|Mix email, SMS, WhatsApp, calls and tasks in a single flow.',
            'Smart branching|Journeys split by course interest, intent score or behaviour.',
            'Wait & window logic|Send at the right hour, pause on holidays, cap frequency.',
            'Per-journey analytics|Conversion at every step, so weak links are obvious.',
            'Templates included|Start from proven admission journeys and adapt.',
        )),
    'products/lead-assignment' => array('g' => 'automation', 't' => 'Lead Assignment',
        'h1' => 'Every Lead, the Right Counsellor, Instantly',
        'sub' => 'Assignment rules that balance load, respect expertise and never let an enquiry sit unowned - even at 2 a.m.',
        'f' => array(
            'Rule-based routing|By course, geography, source, language or campaign.',
            'Round-robin & load balance|Distribute fairly, cap per-counsellor volume.',
            'Skill matching|MBA queries to MBA specialists - automatically.',
            'Instant ownership|The counsellor is notified the second a lead arrives.',
            'Fallback chains|Unaccepted leads re-route before they go cold.',
            'Absence-aware|Leaves and shifts respected without manual re-shuffling.',
        )),
    'products/lead-routing' => array('g' => 'automation', 't' => 'Lead Routing',
        'h1' => 'From Any Source to the Right Queue',
        'sub' => 'Ads, portals, walk-ins, calls and referrals - every channel flows into one router that knows exactly where each enquiry belongs.',
        'f' => array(
            'All sources in|Meta, Google, publishers, forms, IVR and offline - one pipe.',
            'De-dupe on arrival|Repeat enquiries merge into the existing student record.',
            'Priority lanes|High-intent sources jump the queue automatically.',
            'Campus & course routing|Multi-campus groups route to the right team every time.',
            'Source hygiene|UTM and publisher data captured cleanly for ROI reports.',
            'Re-route on signal|A lead that goes hot moves lanes instantly.',
        )),
    'products/task-automation' => array('g' => 'automation', 't' => 'Task Automation',
        'h1' => 'The To-Do List That Writes Itself',
        'sub' => 'Follow-ups, document chases and verification calls appear on the right person\'s list at the right time - done tasks close themselves.',
        'f' => array(
            'Auto-created tasks|Stage changes, missed calls and form fills spawn the next action.',
            'SLA timers|Every task carries a clock; late turns red and escalates.',
            'Ranked worklists|Counsellors open one list, sorted by intent and urgency.',
            'Bulk actions|Update, reassign or close thousands of records in one sweep.',
            'Auto-complete|A task closes itself when the student replies or pays.',
            'Manager view|Live task load and completion per counsellor.',
        )),
    'products/follow-up-automation' => array('g' => 'automation', 't' => 'Follow-up Automation',
        'h1' => 'No Follow-up Ever Slips Again',
        'sub' => 'The platform remembers every promised call, chases every silent student and keeps nudging - politely, on every channel - until there\'s an answer.',
        'f' => array(
            'Auto-scheduled follow-ups|Every conversation books its own next step.',
            'Multi-channel nudges|Missed call -> WhatsApp -> email, in one sequence.',
            'Reminders that chase|Counsellors are pinged before a follow-up is due, not after.',
            'Silence detection|Students who go quiet re-enter nurture automatically.',
            'Best-time sending|Messages go out when each student actually reads them.',
            'Complete history|Every attempt logged on the student\'s timeline.',
        )),
    'products/integrations' => array('g' => 'automation', 't' => 'Integrations',
        'h1' => 'Fits the Stack You Already Run',
        'sub' => 'Fifty-plus native connections - ad platforms, publishers, telephony, payments, forms and ERPs - flowing into one connected Admission CRM.',
        'f' => array(
            'Ad platforms|Meta, Google and LinkedIn leads land in seconds, with full source data.',
            'Education portals|Shiksha, CollegeDekho, Collegedunia and more - auto-captured.',
            'Telephony & IVR|Exotel, Knowlarity and cloud calling, recorded on the lead.',
            'Payments|Razorpay, Easebuzz, PayU and more for fee collection inside the funnel.',
            'Forms & websites|WordPress, Wix, Typeform, Contact Form 7 - every form connected.',
            'Open API|Anything we don\'t ship, your team can connect through the API.',
        )),

    'products/automation' => array('g' => 'automation', 't' => 'Automation',
        'h1' => 'The Automation Suite for Admissions',
        'sub' => 'Workflows, journeys, assignment, routing, tasks and follow-ups - six engines that keep every lead moving without manual effort.',
        'f' => array(
            'Workflow Automation|No-code rules that assign, nurture, escalate and notify.',
            'Journey Builder|The whole student journey on one visual canvas.',
            'Lead Assignment|Every enquiry owned by the right counsellor instantly.',
            'Lead Routing|Every source flowing into the right queue, deduped.',
            'Task Automation|Worklists that build, rank and close themselves.',
            'Follow-up Automation|No promised call or silent student ever slips.',
        )),
    'products/marketing-automation' => array('g' => 'communication', 't' => 'Marketing Automation',
        'h1' => 'Campaigns That Convert to Enrolments',
        'sub' => 'Segmented email, SMS and WhatsApp campaigns wired to your funnel - personalised at scale and measured to admission, not clicks.',
        'f' => array(
            'Smart segments|Target by course, stage, source, geography or behaviour.',
            'Multi-channel sends|Email, SMS and WhatsApp from one composer.',
            'Trigger campaigns|Messages that fire on stage moves and signals.',
            'Personalisation|Name, course and deadline merge in automatically.',
            'A/B testing|Let the better message win, automatically.',
            'Enrolment attribution|Every campaign measured to seats filled.',
        )),
    'products/payment-enrollment' => array('g' => 'automation', 't' => 'Payment & Enrollment',
        'h1' => 'From Offer to Fee Paid, Frictionless',
        'sub' => 'Application and admission fees collected inside the funnel - payment links, gateways, reminders and receipts, reconciled per student.',
        'f' => array(
            'Payment links in-flow|Send collect links on WhatsApp, email or SMS.',
            'Gateway choice|Razorpay, Easebuzz, PayU and more, prewired.',
            'Auto reminders|Polite fee nudges until the payment lands.',
            'Instant reconciliation|Every payment tied to the right student.',
            'Receipts & records|Automatic acknowledgements, full history.',
            'Enrolment trigger|A paid fee moves the student forward on its own.',
        )),
    'security' => array('g' => 'security', 't' => 'Security',
        'h1' => 'Enterprise-Grade Trust, Built In',
        'sub' => 'Roles, permissions, audit trails, hardened infrastructure and certifications - the complete security posture your institution\'s data deserves.',
        'f' => array(
            'Role Management|The right access for every role, in minutes.',
            'Permissions|Granular control down to a single field.',
            'Audit Logs|Every view, edit and export on the record.',
            'Data Security|Encryption everywhere, India data residency.',
            'Compliance|ISO 27001 certified and GDPR-ready.',
            'Reliability|99.9% uptime with 24x7 monitoring.',
        )),
    'products/communication' => array('g' => 'communication', 't' => 'Communication',
        'h1' => 'Every Channel. One Conversation.',
        'sub' => 'Chatbot, WhatsApp, telephony, IVR, email and SMS - every student conversation from one place, logged on one timeline.',
        'f' => array(
            'Education Chatbot|24x7 AI answers on your website and WhatsApp.',
            'WhatsApp Business API|Official, verified, journey-connected.',
            'Cloud Telephony|Click-to-call with recordings on the lead.',
            'IVR|Inbound callers routed right, every time.',
            'Email & SMS|Campaigns and triggers from the same composer.',
            'Mobile CRM|The whole conversation in your pocket.',
        )),
    'products/education-chatbot' => array('g' => 'communication', 't' => 'Education Chatbot',
        'h1' => 'The Counsellor That Never Logs Off',
        'sub' => 'An AI chatbot trained on your courses, fees and deadlines - answering on your website and WhatsApp in 95+ languages, 24x7.',
        'f' => array(
            'Answers instantly|Fees, courses, scholarships, deadlines - solved in seconds.',
            'Your knowledge|Trained on your programmes, not generic replies.',
            '95+ languages|Students ask in their language, it answers in kind.',
            'Lead capture|Every chat becomes a qualified lead in the CRM.',
            'Human handoff|Hot conversations route to counsellors with context.',
            'Always learning|Every season makes it sharper.',
        )),
    'products/whatsapp-business-api' => array('g' => 'communication', 't' => 'WhatsApp Business API',
        'h1' => 'Official WhatsApp for Admissions',
        'sub' => 'Verified sender, 98% open rates, rich templates and real two-way threads - every message logged on the student\'s timeline.',
        'f' => array(
            'Official API|Green-tick verified, zero ban risk.',
            'Rich broadcasts|Brochures, forms and payment links in-thread.',
            'Auto-replies|Course and fee questions answered instantly, 24x7.',
            'Two-way threads|Real conversations, routed to counsellors when needed.',
            'Journey-connected|WhatsApp steps inside your nurture flows.',
            'CRM-logged|Every message on the lead, forever.',
        )),
    'products/cloud-telephony' => array('g' => 'communication', 't' => 'Cloud Telephony',
        'h1' => 'Every Call, Connected to the Lead',
        'sub' => 'Click-to-call from the CRM, automatic recording and logging, and smart routing - telephony that behaves like part of the funnel.',
        'f' => array(
            'Click-to-call|Dial from the lead card - no number juggling.',
            'Auto-logging|Duration, outcome and recording saved on the student.',
            'Call recording|Review and coach on real conversations.',
            'Smart routing|Inbound calls reach the right counsellor.',
            'Missed-call capture|Every missed call becomes a follow-up task.',
            'Provider choice|Exotel, Knowlarity and more, prewired.',
        )),
    'products/email-marketing' => array('g' => 'communication', 't' => 'Email Marketing',
        'h1' => 'Email That Students Actually Open',
        'sub' => 'Beautiful templates, smart segments and trigger-based sends - admission email measured to enrolment, not opens.',
        'f' => array(
            'Drag-drop templates|On-brand emails without a designer.',
            'Smart segments|Course, stage and behaviour targeting.',
            'Trigger sends|Emails that fire exactly when a lead acts.',
            'Deliverability|SendGrid, MSG91, Netcore - prewired and warmed.',
            'A/B testing|Subject lines that earn their opens.',
            'Enrolment tracking|Every campaign measured to admissions.',
        )),
    'products/sms-marketing' => array('g' => 'communication', 't' => 'SMS Marketing',
        'h1' => 'The Channel That Always Gets Read',
        'sub' => 'Transactional and campaign SMS with sender IDs, DLT compliance and CRM logging - the reliable nudge in every journey.',
        'f' => array(
            'Campaign SMS|Segmented sends from the CRM composer.',
            'Transactional SMS|OTPs, confirmations and fee alerts, instant.',
            'DLT compliant|Templates and sender IDs handled properly.',
            'Journey steps|SMS nudges inside automated flows.',
            'Link tracking|Know who clicked, feed it to scoring.',
            'CRM-logged|Every SMS on the student timeline.',
        )),
    /* ── SECURITY (security/*) ───────────────────────────────────────── */
    'security/role-management' => array('g' => 'security', 't' => 'Role Management',
        'h1' => 'The Right Access for Every Role',
        'sub' => 'Counsellors, team leads, marketing and management each see exactly what their job needs - nothing more, nothing less.',
        'f' => array(
            'Ready-made roles|Counsellor, TL, admin and management presets out of the box.',
            'Custom roles|Compose any role from granular capabilities.',
            'Team hierarchies|Campus, region and brand structures mirrored in access.',
            'Data scoping|Each user sees only their own leads, team or campus.',
            'One-click transitions|Promotions and exits handled without IT tickets.',
            'Access reviews|Periodic reports of who can see what.',
        )),
    'security/permissions' => array('g' => 'security', 't' => 'Permissions',
        'h1' => 'Granular Control, Down to a Field',
        'sub' => 'Decide who can view, edit, export or delete - per module, per stage, even per field like phone numbers and fee data.',
        'f' => array(
            'Module-level control|Turn whole modules on or off per role.',
            'Field-level masking|Hide phone numbers or fees from roles that don\'t need them.',
            'Export governance|Downloads restricted, watermarked and logged.',
            'Bulk-action limits|Only trusted roles touch thousands of records at once.',
            'Stage gates|Sensitive stages editable only by authorised roles.',
            'API scopes|Integrations get the narrowest access that works.',
        )),
    'security/audit-logs' => array('g' => 'security', 't' => 'Audit Logs',
        'h1' => 'Every Action, On the Record',
        'sub' => 'Who viewed, who edited, who exported, when and from where - a complete, tamper-evident trail your auditors will love.',
        'f' => array(
            'Full activity trail|Logins, views, edits, deletes and exports - all captured.',
            'Per-record history|Open any student and see every touch on a timeline.',
            'Search & filter|Slice the trail by user, action, module or date in seconds.',
            'Export for audit|Hand auditors exactly the window they ask for.',
            'Anomaly visibility|Unusual export volumes or access patterns stand out.',
            'Retention you control|Keep the trail as long as your policy demands.',
        )),
    'security/data-security' => array('g' => 'security', 't' => 'Data Security',
        'h1' => 'Student Data, Protected by Design',
        'sub' => 'Encryption in transit and at rest, hardened infrastructure, India data residency and disciplined engineering practice - security is the default.',
        'f' => array(
            'Encrypted everywhere|TLS in transit, AES-256 at rest.',
            'India data residency|Student data stays in-country.',
            'Hardened infrastructure|Isolated environments, least-privilege operations.',
            'Backups & recovery|Automated backups with tested restore drills.',
            'PII minimisation|Collect what admissions needs - nothing extra.',
            'Continuous monitoring|24x7 alerting on the platform\'s health and access.',
        )),
    'security/compliance' => array('g' => 'security', 't' => 'Compliance',
        'h1' => 'Certified. Compliant. Audit-Ready.',
        'sub' => 'ISO 27001 certified and GDPR-ready, with the policies, processes and paperwork your institution\'s reviews ask for.',
        'f' => array(
            'ISO 27001|Certified information-security management.',
            'GDPR-ready|Consent, purpose limitation and erasure workflows built in.',
            'DPAs on request|Standard agreements ready for your legal team.',
            'Consent tracking|When and how each student opted in, on the record.',
            'Right to erasure|Honour deletion requests without engineering effort.',
            'Vendor reviews|Security questionnaires answered fast, with evidence.',
        )),

    /* ── ANALYTICS (analytics/*) ─────────────────────────────────────── */
    'products/analytics' => array('g' => 'analytics', 't' => 'Analytics',
        'h1' => 'Decide on Numbers, Not Anecdotes',
        'sub' => 'Six analytics products over one live data model - from the executive dashboard to custom reports, every admission answer is a click away.',
        'f' => array(
            'Executive Dashboard|The whole season on one live screen.',
            'Admission Analytics|Every funnel stage measured and moving.',
            'Marketing Analytics|Every rupee tracked to enrolment.',
            'Lead Analytics|Quality, intent and outcome per lead.',
            'Funnel Analytics|Find the leak costing you admissions.',
            'Custom Reports|Any question, answered and scheduled.',
        )),
    'analytics/executive-dashboard' => array('g' => 'analytics', 't' => 'Executive Dashboard',
        'h1' => 'Your Whole Admission Season, One Screen',
        'sub' => 'The numbers a director actually asks for - enquiries, conversions, cost, revenue and team output - live, not in next week\'s deck.',
        'f' => array(
            'Season at a glance|Enquiry -> application -> enrolment, against target.',
            'Revenue & ROI|Fee revenue influenced and cost per enrolment by source.',
            'Team scoreboard|Counsellor output and conversion, ranked live.',
            'Campus & course cuts|Compare programmes and campuses side by side.',
            'Trend lines|This cycle vs last, week by week.',
            'Boardroom-ready|Export any view straight into your review deck.',
        )),
    'analytics/admission-analytics' => array('g' => 'analytics', 't' => 'Admission Analytics',
        'h1' => 'See Exactly Where Admissions Stand',
        'sub' => 'Every stage of the funnel measured - so you know what\'s moving, what\'s stuck and what needs attention this week, not after the cycle.',
        'f' => array(
            'Live funnel|Real-time counts and conversion at every stage.',
            'Stage velocity|How long leads sit per stage - and where they stall.',
            'Cohort tracking|Follow each intake batch from enquiry to fee.',
            'Drop-off reasons|Why students leave the funnel, quantified.',
            'Target tracking|Seats filled vs target, by course and campus.',
            'Drill to the lead|Every number opens into the students behind it.',
        )),
    'analytics/marketing-analytics' => array('g' => 'analytics', 't' => 'Marketing Analytics',
        'h1' => 'Know What Every Rupee of Marketing Did',
        'sub' => 'Source, campaign and publisher performance measured to enrolment - not clicks - so budgets flow to what actually fills seats.',
        'f' => array(
            'Source ROI|Cost per enquiry AND per enrolment, by channel.',
            'Campaign drill-down|Meta, Google and publisher campaigns compared honestly.',
            'Publisher scorecards|Which portals send students who actually join.',
            'UTM integrity|Clean attribution captured automatically at the lead.',
            'Spend pacing|Burn vs seats filled, all season.',
            'Wasted-spend alerts|Sources that never convert get flagged.',
        )),
    'analytics/lead-analytics' => array('g' => 'analytics', 't' => 'Lead Analytics',
        'h1' => 'Understand Every Lead You Own',
        'sub' => 'Quality, intent, engagement and outcome for every enquiry - so effort goes where enrolment is likeliest.',
        'f' => array(
            'Quality scoring|Every lead graded by fit and behaviour.',
            'Intent signals|Opens, replies, visits and call outcomes rolled into one score.',
            'Response-time truth|Actual first-response and follow-up times, per team.',
            'Aging view|Untouched and overdue leads surfaced before they die.',
            'Source quality|Which sources send serious students - not just volume.',
            'Outcome loops|Won/lost reasons feed back into scoring.',
        )),
    'analytics/funnel-analytics' => array('g' => 'analytics', 't' => 'Funnel Analytics',
        'h1' => 'Find the Leak. Fix the Funnel.',
        'sub' => 'Stage-to-stage conversion, time-in-stage and drop-off - visualised so the one bottleneck costing you admissions is impossible to miss.',
        'f' => array(
            'Visual funnel|The classic funnel, live and clickable.',
            'Stage conversion|Exact percentage moving between every pair of stages.',
            'Bottleneck finder|The stage bleeding the most students, highlighted.',
            'Segment funnels|Compare funnels by course, source or campus.',
            'Time-in-stage|Where days are lost between enquiry and enrolment.',
            'What-if math|See what fixing one stage does to total enrolments.',
        )),
    'analytics/custom-reports' => array('g' => 'analytics', 't' => 'Custom Reports',
        'h1' => 'Any Question. Answered in a Report.',
        'sub' => 'A drag-and-drop report builder over every field in your CRM - build it once, schedule it forever, share it with exactly the right people.',
        'f' => array(
            'Report builder|Rows, columns, filters and math - no SQL, no exports.',
            'Every field available|Report on anything the CRM captures, including custom fields.',
            'Scheduled delivery|Monday-morning reports land in inboxes automatically.',
            'Role-safe sharing|Viewers see only the data their role allows.',
            'Saved views|One click back to any report you use weekly.',
            'VidyaGPT analytics|Ask for a report in plain language - get it built.',
        )),

    /* ── SOLUTIONS: TEAMS (solutions/*) ──────────────────────────────── */
    'solutions/admissions' => array('g' => 'teams', 't' => 'For Admission Teams',
        'h1' => 'The Operating System for Admission Teams',
        'sub' => 'One queue, one timeline per student and AI doing the first mile - so the team\'s day is conversations, not coordination.',
        'f' => array(
            'One shared pipeline|Every enquiry, stage and owner visible to the whole team.',
            'AI first response|Every enquiry answered in seconds, around the clock.',
            'Ranked worklists|Each counsellor opens the day knowing exactly whom to call.',
            'Complete timelines|Calls, messages and notes on one student card.',
            'Team targets|Seats, calls and conversions tracked live.',
            'Zero lead leakage|Nothing sits unowned, ever.',
        )),
    'solutions/marketing' => array('g' => 'teams', 't' => 'For Marketing Teams',
        'h1' => 'Marketing That Proves Its Enrolments',
        'sub' => 'Every campaign wired to the funnel - so marketing reports enrolments and cost per seat, not clicks and impressions.',
        'f' => array(
            'Closed-loop attribution|Ad to enquiry to enrolment, connected automatically.',
            'Campaign command|Segmented email, SMS and WhatsApp from one place.',
            'Lead quality feedback|Sales outcomes flow back to optimise targeting.',
            'Publisher accountability|Portal performance measured to admission.',
            'Landing-page speed|Forms connect in minutes, leads route instantly.',
            'Budget confidence|Shift spend to sources that fill seats.',
        )),
    'solutions/sales' => array('g' => 'teams', 't' => 'For Sales Teams',
        'h1' => 'Close More Enrolments, With Less Chasing',
        'sub' => 'Prioritised pipelines, auto-logged activity and AI that warms every lead before your first call.',
        'f' => array(
            'Priority pipeline|Hottest, highest-intent leads always on top.',
            'Auto-logged activity|Calls, messages and outcomes recorded without typing.',
            'Next best action|The platform suggests the move most likely to convert.',
            'Instant callbacks|Click-to-call with recordings on the record.',
            'Objection history|Every past conversation at your fingertips mid-call.',
            'Honest forecasts|Pipeline value and likelihood, live.',
        )),
    'solutions/counselors' => array('g' => 'teams', 't' => 'For Counsellors',
        'h1' => 'A Calmer, Sharper Counsellor Day',
        'sub' => 'One ranked list, every student\'s full story on one card, and the busywork - logging, reminders, first replies - done by the platform.',
        'f' => array(
            'Today\'s list, ranked|Open one screen and start with the right student.',
            'Full student card|Course interest, history and documents in one view.',
            'No manual logging|Conversations record themselves.',
            'Reminders that chase|The system nags before something is late.',
            'Warm handoffs|AI shares the whole context when passing a student.',
            'Personal scoreboard|See your own conversions grow.',
        )),
    'solutions/management' => array('g' => 'teams', 't' => 'For Management',
        'h1' => 'Run Admissions on Numbers, Not Anecdotes',
        'sub' => 'Live visibility across campuses, honest team metrics and season forecasts - the control room for the whole admission engine.',
        'f' => array(
            'Executive dashboard|The season\'s truth on one screen, live.',
            'Cross-campus view|Every campus and course compared honestly.',
            'Team accountability|Response times and conversions per counsellor.',
            'Cost per enrolment|What each seat actually cost, by source.',
            'Forecasting|Where the season lands if this week continues.',
            'Anywhere access|The same picture on your phone.',
        )),
    'solutions/call-center' => array('g' => 'teams', 't' => 'For Call Centers',
        'h1' => 'An Admission Call Center That Never Sleeps',
        'sub' => 'AI voice agents take the first call in seconds, humans take the warm ones - with dialers, recordings and QA built in.',
        'f' => array(
            'AI voice first-response|Every enquiry called back within 30 seconds, 24x7.',
            'Smart dialers|Auto-dial ranked lists; skip voicemails and dead numbers.',
            'Call recording & QA|Every call recorded, searchable and scoreable.',
            'IVR flows|Route inbound callers to the right team, always.',
            'Multi-language|Serve students in 95+ languages on chat and voice.',
            'Live wallboards|Queues, wait times and outcomes at a glance.',
        )),

    /* ── SOLUTIONS: USE CASES (solutions/*) ──────────────────────────── */
    'solutions/student-recruitment' => array('g' => 'usecase', 't' => 'Student Recruitment',
        'h1' => 'Recruit Students at Full Speed',
        'sub' => 'Capture every channel, respond first, and nurture until enrolment - the complete recruitment engine on one platform.',
        'f' => array(
            'Every source captured|Ads, portals, events, walk-ins and referrals in one pipeline.',
            'Speed to lead|First response in seconds - before competing institutes call.',
            'Always-on nurture|Journeys keep every prospect warm to decision day.',
            'Recruiter productivity|Ranked lists and auto-logging double daily output.',
            'Agent & partner leads|Channel partners tracked with full transparency.',
            'Season analytics|Know your best sources before you spend again.',
        )),
    'solutions/lead-management' => array('g' => 'usecase', 't' => 'Lead Management',
        'h1' => 'Every Lead Captured. None Forgotten.',
        'sub' => 'Auto-capture, de-duplication, one timeline per student and disciplined follow-up - lead management that actually manages itself.',
        'f' => array(
            'Zero-loss capture|Every channel lands in the CRM automatically.',
            'De-duplication|One student, one record - however many times they enquire.',
            'Full timelines|Every interaction on one card, forever.',
            'Ownership rules|Every lead has exactly one accountable owner.',
            'Aging alerts|Untouched leads surface before they go cold.',
            'Clean data|Bulk import, verify and enrich inside the platform.',
        )),
    'solutions/admission-automation' => array('g' => 'usecase', 't' => 'Admission Automation',
        'h1' => 'Automate the Admission Grind',
        'sub' => 'From first reply to fee reminder - the repetitive 80% of admissions runs itself, and your team owns the conversations that matter.',
        'f' => array(
            'Instant first replies|Every enquiry acknowledged and qualified by AI.',
            'Document chasing|Missing documents requested and tracked automatically.',
            'Application nudges|Started-but-stuck applications get gentle pushes.',
            'Fee reminders|Offer to payment, chased politely on schedule.',
            'Status updates|Students informed at every stage without counsellor effort.',
            'Exception surfacing|Humans only see the cases that need judgement.',
        )),
    'solutions/ai-calling' => array('g' => 'usecase', 't' => 'AI Calling',
        'h1' => 'The AI That Calls Every Lead First',
        'sub' => 'VidyaAI voice agents call new enquiries in seconds, qualify intent in natural conversation and book counsellor slots - in 95+ languages.',
        'f' => array(
            '30-second callback|Every new enquiry called while interest is peak.',
            'Natural conversations|Students talk normally; the AI understands courses and fees.',
            'Intent scoring|Every call ends with a graded, summarised lead.',
            'Counsellor booking|Hot leads land on a human calendar instantly.',
            'Recordings & transcripts|Every AI call on the record, reviewable.',
            'Endless capacity|Admission-season spikes without hiring spikes.',
        )),
    'solutions/whatsapp-automation' => array('g' => 'usecase', 't' => 'WhatsApp Automation',
        'h1' => 'Admissions on the Channel Students Read',
        'sub' => 'Official WhatsApp Business API - instant replies, rich campaigns and two-way conversations, every message logged on the lead.',
        'f' => array(
            'Official API|Verified sender, green tick, zero ban risk.',
            '98% open rates|Messages that actually get read.',
            'Auto-replies 24x7|Course, fee and deadline questions answered instantly.',
            'Rich broadcasts|Brochures, forms and payment links in-thread.',
            'Two-way threads|Real conversations, routed to counsellors when needed.',
            'CRM-logged|Every message on the student\'s timeline.',
        )),
    'solutions/student-engagement' => array('g' => 'usecase', 't' => 'Student Engagement',
        'h1' => 'Keep Every Student Warm to Day One',
        'sub' => 'Personalised, well-timed touches across channels - so admitted students stay excited and melt (summer or otherwise) stays low.',
        'f' => array(
            'Personalised journeys|Content by course, stage and behaviour.',
            'Multi-channel presence|WhatsApp, email, SMS and calls in concert.',
            'Event invitations|Webinars, campus visits and open days, managed end to end.',
            'Engagement scoring|Know who\'s cooling off before they leave.',
            'Community moments|Milestones celebrated automatically.',
            'Melt prevention|Offer-to-join drop-off actively defended.',
        )),
    'solutions/event-management' => array('g' => 'usecase', 't' => 'Event Management',
        'h1' => 'Admission Events That Fill Themselves',
        'sub' => 'Webinars, fairs, open days and counselling camps - invitations, registrations, reminders and follow-ups all run from the CRM.',
        'f' => array(
            'Registration pages|Branded sign-up in minutes, synced to the CRM.',
            'Smart invitations|Invite exactly the right segment per event.',
            'Automated reminders|Show-up rates lifted by timed nudges.',
            'Check-in capture|Walk-ins become leads on the spot.',
            'Post-event follow-up|Every attendee enters the right journey after.',
            'Event ROI|Enrolments per event, not just footfall.',
        )),
    'solutions/application-processing' => array('g' => 'usecase', 't' => 'Application Processing',
        'h1' => 'Applications Without the Paper Chase',
        'sub' => 'Online forms, document collection, verification and fee payment on one rail - with students updated at every step.',
        'f' => array(
            'Online applications|Mobile-friendly forms students actually finish.',
            'Document collection|Uploads chased, checked and stored per student.',
            'Verification workflow|Review queues with clear accept/query/reject.',
            'Integrated payments|Application and admission fees collected in-flow.',
            'Status transparency|Students always know where they stand.',
            'Merit & shortlists|Score, rank and release decisions from one place.',
        )),
    'solutions/lead-scoring' => array('g' => 'usecase', 't' => 'Lead Scoring',
        'h1' => 'Call the Right Student First, Every Time',
        'sub' => 'AI-graded intent from behaviour, conversations and profile - so the day\'s effort always starts with the likeliest enrolment.',
        'f' => array(
            'Behavioural signals|Opens, clicks, replies, visits - all counted.',
            'Conversation intent|AI reads calls and chats for real buying intent.',
            'Profile fit|Course, budget and geography matched to your programmes.',
            'Live re-scoring|Scores update the moment behaviour changes.',
            'Prediction score|Enrolment likelihood on every lead card.',
            'Prioritised queues|Worklists ordered by score automatically.',
        )),

    'solutions/admission-management' => array('g' => 'usecase', 't' => 'Admission Management',
        'h1' => 'Every Applicant, One Live Pipeline',
        'sub' => 'Track every applicant from enquiry to admission on one board - stages, owners, documents and deadlines always current.',
        'f' => array(
            'Live pipeline|Every applicant\'s exact stage, visible to the whole team.',
            'Clear ownership|One accountable counsellor per applicant, always.',
            'Document tracking|What\'s submitted, missing and verified - per student.',
            'Deadline discipline|Intake dates and follow-ups that never slip.',
            'Multi-course handling|Parallel applications managed without confusion.',
            'Stage analytics|Where applicants stall, quantified weekly.',
        )),
    'solutions/enrollment-management' => array('g' => 'usecase', 't' => 'Enrollment Management',
        'h1' => 'From Offer Letter to Fee Paid, Faster',
        'sub' => 'The last mile of admissions managed actively - offers, acceptances, fee collection and onboarding on one rail.',
        'f' => array(
            'Offer tracking|Every offer\'s status - sent, viewed, accepted - live.',
            'Fee collection in-flow|Payment links and reminders until the seat is paid.',
            'Melt defence|Silent admits re-engaged before they slip away.',
            'Onboarding steps|Documents, kits and welcomes triggered on payment.',
            'Seat visibility|Filled vs target by course, updated live.',
            'Handover clean|Enrolled students packaged for the academic team.',
        )),
    'solutions/walk-in-management' => array('g' => 'usecase', 't' => 'Walk-in Management',
        'h1' => 'No Campus Visit Ever Goes Unrecorded',
        'sub' => 'Front-desk capture, instant assignment and disciplined follow-up - every walk-in becomes a tracked lead the moment they arrive.',
        'f' => array(
            'Quick capture|A 30-second front-desk form logs every visitor.',
            'Instant assignment|The right counsellor is notified while the family waits.',
            'Visit notes|What was discussed, promised and quoted - recorded.',
            'Same-day follow-up|Thank-you and next-step messages fire automatically.',
            'Repeat-visit memory|Returning families recognised with full history.',
            'Walk-in analytics|Footfall to admission conversion, measured.',
        )),
    'solutions/study-abroad-crm' => array('g' => 'abroad', 't' => 'Study Abroad CRM',
        'h1' => 'The CRM Built for Study-Abroad Consultancies',
        'sub' => 'Country, course and intake pipelines with agent visibility, document workflows and commission clarity - purpose-built, not adapted.',
        'f' => array(
            'Country-course pipelines|Track students by destination, university and intake.',
            'Intake calendars|Deadlines per country and university, never missed.',
            'Document workflows|SOPs, transcripts and visa papers chased and checked.',
            'University shortlists|Options, applications and offers per student.',
            'Agent network|Sub-agent leads tracked with full transparency.',
            'Multi-branch view|Every branch and counsellor on one dashboard.',
        )),
    'solutions/education-agents' => array('g' => 'abroad', 't' => 'Education Agents',
        'h1' => 'Run Your Agent Network With Total Clarity',
        'sub' => 'Onboard sub-agents, track their students, settle commissions and see exactly which partners actually deliver enrolments.',
        'f' => array(
            'Agent onboarding|Partners live with their own tracked funnel in minutes.',
            'Lead attribution|Every student tied to the agent who sent them.',
            'Agent portals|Partners see their own pipeline - and only theirs.',
            'Commission clarity|Conversions and payouts computed transparently.',
            'Performance ranking|Your best- and worst-performing partners, visible.',
            'Duplicate protection|One student claimed by two agents - resolved fairly.',
        )),
    'solutions/education-consultants' => array('g' => 'abroad', 't' => 'Education Consultants',
        'h1' => 'Counsellor Workflows for Visa, Docs & Apps',
        'sub' => 'From first counselling session to visa stamp - every step, document and deadline of every student managed on one timeline.',
        'f' => array(
            'Counselling records|Preferences, budgets and shortlists per student.',
            'Application tracking|Every university application\'s live status.',
            'Visa workflows|Checklists, appointments and outcomes managed.',
            'Document vault|Every certificate and SOP, versioned per student.',
            'Service billing|Consulting fees invoiced and tracked in-flow.',
            'Season repeatability|This year\'s process becomes next year\'s playbook.',
        )),
    'solutions/lead-nurturing' => array('g' => 'usecase', 't' => 'Lead Nurturing',
        'h1' => 'Keep Every Lead Warm Until Decision Day',
        'sub' => 'Automated drips across WhatsApp, email and SMS that mature not-yet-ready students instead of letting them go cold.',
        'f' => array(
            'Multi-channel drips|WhatsApp, email and SMS sequences in concert.',
            'Behaviour-triggered|Opens, clicks and silences change the track.',
            'Content that helps|Course guides, fee plans and deadlines - not spam.',
            'Best-time delivery|Messages land when each student actually reads.',
            'Warmth scoring|Know exactly when a nurtured lead turns hot.',
            'Counsellor alerts|Humans step in at the moment of intent.',
        )),
    'solutions/enrollment-crm' => array('g' => 'usecase', 't' => 'Enrollment CRM',
        'h1' => 'One CRM From First Touch to Enrolled',
        'sub' => 'Capture, engage, apply, pay, enrol - the complete student lifecycle on a single platform built only for education.',
        'f' => array(
            'Full lifecycle|Enquiry to enrolment without switching tools.',
            'AI at every step|Instant replies, calling, scoring and follow-ups.',
            'Application + payment|Forms, documents and fees on the same rail.',
            'Team workspace|Counsellors, marketing and management in one system.',
            'Education-native|Courses, batches, intakes and agents built in.',
            'Season analytics|Every cycle measured, every cycle improved.',
        )),

    /* ── SOLUTIONS: OUTCOMES (solutions/*) ───────────────────────────── */
    'solutions/better-student-experience' => array('g' => 'outcome', 't' => 'Better Student Experience',
        'h1' => 'Admissions Students Actually Enjoy',
        'sub' => 'Instant answers, one consistent conversation and total clarity on next steps - the experience that wins students before the seat does.',
        'f' => array(
            'Instant answers|No student waits hours for a reply, ever.',
            'One conversation|Context follows the student across channels and people.',
            'Clear next steps|Everyone always knows what happens next.',
            'Their channel|WhatsApp, call or email - the student chooses.',
            'Their language|95+ languages on chat and voice.',
            'No repeat questions|The platform remembers so students never re-explain.',
        )),
    'solutions/faster-follow-ups' => array('g' => 'outcome', 't' => 'Faster Follow-ups',
        'h1' => 'From Hours of Delay to 30 Seconds',
        'sub' => 'The institute that responds first wins the admission - AI answers instantly and disciplined queues keep every follow-up on time.',
        'f' => array(
            '30-second response|AI engages every enquiry the moment it lands.',
            '12x faster than manual|Measured across 500+ institutions.',
            'Never-miss queues|Every promised call has an owner and a clock.',
            'Escalating nudges|Late follow-ups climb the chain automatically.',
            'After-hours coverage|Evenings, weekends and holidays handled by AI.',
            'Response analytics|Team speed measured honestly, improved weekly.',
        )),
    'solutions/increase-roi' => array('g' => 'outcome', 't' => 'Increase ROI',
        'h1' => 'More Enrolments Per Rupee Spent',
        'sub' => 'Kill wasted spend, convert more of the leads you already pay for, and lower the cost of every seat filled.',
        'f' => array(
            'Cost per enrolment|The metric that matters, by source, live.',
            'Wasted-spend detection|Sources that never convert, flagged.',
            'Higher conversion|More admissions from the same lead volume.',
            'Counsellor leverage|40% more output without headcount.',
            'Automation savings|Repetitive work hours returned every week.',
            'ROI calculator|Model your upside before you commit.',
        )),
    'solutions/reduce-manual-work' => array('g' => 'outcome', 't' => 'Reduce Manual Work',
        'h1' => 'Give Your Team Their Hours Back',
        'sub' => 'Data entry, first replies, reminders, reports - the platform absorbs the drudgery so people do only what people are for.',
        'f' => array(
            'Zero data entry|Leads, calls and messages log themselves.',
            'Auto first response|The biggest time sink, fully automated.',
            'Bulk everything|Update thousands of records in one action.',
            'Self-building reports|Numbers arrive scheduled - no spreadsheet nights.',
            'Document automation|Collection and verification chased by the system.',
            'A season\'s data entry|Becomes one afternoon of review.',
        )),
    'solutions/improve-conversion' => array('g' => 'outcome', 't' => 'Improve Conversion',
        'h1' => 'Turn More Enquiries Into Admissions',
        'sub' => 'Respond first, prioritise best-fit students, follow up forever and fix funnel leaks - conversion rises at every stage.',
        'f' => array(
            'Speed wins seats|First responder converts - AI makes it always you.',
            'Best-fit focus|Scoring points effort at the likeliest enrolments.',
            'Leak-proof funnel|Analytics expose exactly where students drop.',
            'Persistent nurture|Not-yet-ready leads mature instead of dying.',
            'Sharper conversations|Full context makes every call count.',
            '+37% conversions|The measured average across our institutions.',
        )),
    'solutions/increase-admissions' => array('g' => 'outcome', 't' => 'Increase Admissions',
        'h1' => 'Fill More Seats. Same Team. Same Budget.',
        'sub' => 'Everything on this platform - speed, prioritisation, automation, analytics - exists for one number: admissions closed.',
        'f' => array(
            'More from every source|Zero leakage means more real prospects in play.',
            'More from every lead|Faster, smarter follow-up converts the margin.',
            'More from every counsellor|Productivity tools raise per-person closes.',
            'More from every rupee|Budget flows to sources that fill seats.',
            'Season compounding|Each cycle starts smarter than the last.',
            '2x conversions|What institutions report after switching.',
        )),

    /* ── INDUSTRIES (industries/*-crm - extraaedge.com's canonical slugs,
       so existing search traffic lands on the same URLs) ─────────────── */
    'industries/higher-education-crm' => array('g' => 'institution', 't' => 'Higher Education CRM',
        'h1' => 'Admissions for Universities & Colleges',
        'sub' => 'Multi-campus, multi-programme funnels unified on one platform - shared visibility for leadership, autonomy for every department, and every seat filled.',
        'f' => array(
            'Multi-campus control|Every campus and school on one dashboard, honestly compared.',
            'Programme pipelines|UG, PG and doctoral funnels tracked separately, reported together.',
            'Speed to lead|First response in seconds - before the institute next door.',
            'Cut-off & merit flows|Shortlists, offers and admissions managed cleanly.',
            'Central analytics|Leadership view: seats, sources and spend, live.',
            'Enterprise trust|ISO 27001, roles, audit logs and data residency.',
        )),
    'industries/school-crm' => array('g' => 'institution', 't' => 'School CRM',
        'h1' => 'Parent-First School Admissions',
        'sub' => 'Trust-building journeys for K-12 - every parent enquiry answered instantly, every campus visit followed up, every admission decision made easy.',
        'f' => array(
            'Parent journeys|Communication written for parents, timed for evenings.',
            'Walk-in & tour capture|Every campus visit becomes a tracked family.',
            'WhatsApp-first|The channel parents actually read, officially.',
            'Sibling & referral memory|Families recognised across years and children.',
            'Season calendars|Admission windows and document deadlines managed.',
            'Front-desk simple|Reception staff productive on day one.',
        )),
    'industries/edtech-crm' => array('g' => 'institution', 't' => 'EdTech CRM',
        'h1' => 'CRM for High-Velocity EdTech Funnels',
        'sub' => 'Thousands of digital leads a day, qualified by AI and routed to closers - without hiring a floor of SDRs.',
        'f' => array(
            'Volume without chaos|Tens of thousands of leads a week, deduped and routed.',
            'Instant qualification|AI calls and scores every signup in seconds.',
            'Funnel experimentation|Sources, offers and journeys A/B tested honestly.',
            'Sales-floor tooling|Dialers, queues and scoreboards for closers.',
            'CAC discipline|Cost per paid enrolment by channel, live.',
            'API-first|Your product events flow straight into the funnel.',
        )),
    'industries/vocational-crm' => array('g' => 'institution', 't' => 'Vocational CRM',
        'h1' => 'Enrolments for Skill & Vocational Training',
        'sub' => 'Short courses, rolling batches and career-driven students - an admission engine tuned for the pace of vocational education.',
        'f' => array(
            'Rolling-batch funnels|Continuous intakes managed without confusion.',
            'Career-outcome selling|Placement stories and outcomes in every journey.',
            'Fast decision cycles|Enquiry to enrolment in days, supported by AI.',
            'Multi-course cross-sell|Alumni nurtured into the next certification.',
            'Centre operations|Every training centre on one dashboard.',
            'Affordable plans|Sized for single centres and national chains.',
        )),
    'industries/coaching-institute-crm' => array('g' => 'institution', 't' => 'Coaching Institute CRM',
        'h1' => 'Batch-Deadline Admissions, Leak-Proof',
        'sub' => 'When batches fill on dates, speed is everything - capture, counsel and enrol students before the batch starts, at walk-in volume.',
        'f' => array(
            'Batch-driven funnels|Enquiries mapped to batches and start dates.',
            'Same-hour response|AI answers while the student is still deciding.',
            'Walk-in heavy|Front-desk capture built for daily footfall.',
            'Scholarship & test flows|Entrance tests and discounts managed in-funnel.',
            'Multi-centre view|Every branch compared on one screen.',
            'Re-enrolment|Next-course nurture for every passing-out batch.',
        )),
    'industries/overseas-crm' => array('g' => 'institution', 't' => 'Overseas Education CRM',
        'h1' => 'The Platform for Study-Abroad Businesses',
        'sub' => 'Country pipelines, agent networks and document workflows - everything an overseas-education business runs on, in one place.',
        'f' => array(
            'Country-course pipelines|Students tracked by destination and intake.',
            'Agent transparency|Every sub-agent\'s funnel, visible and attributed.',
            'Document workflows|SOPs, transcripts and visa papers chased automatically.',
            'University deadlines|Intake calendars that never let a date slip.',
            'Branch operations|Every office and counsellor on one dashboard.',
            'Commission clarity|Conversions and payouts computed cleanly.',
        )),

        /* ── PROOF ───────────────────────────────────────────────────────── */
    'case-studies' => array('g' => 'proof', 't' => 'Case Studies',
        'h1' => 'How Institutions Win With ExtraaEdge',
        'sub' => 'Deep dives into real admission transformations - the problem, the rollout and the measured results, in the institution\'s own numbers.',
        'f' => array(
            'Universities|Multi-campus funnels unified and accelerated.',
            'Colleges|Counsellor productivity doubled in one season.',
            'Study abroad|Country-course pipelines with full agent visibility.',
            'EdTech|High-volume funnels handled without hiring waves.',
            'Coaching & training|Batch-deadline admissions that never leak.',
            'K-12 & preschools|Parent journeys built on trust and speed.',
        )),
    'testimonials' => array('g' => 'proof', 't' => 'Testimonials',
        'h1' => 'In Our Customers\' Own Words',
        'sub' => 'Directors, admission heads and counsellors on what changed after ExtraaEdge - watch the stories, hear the numbers.',
        'f' => array(
            'Leadership voices|Directors on visibility, ROI and control.',
            'Admission heads|Process, speed and season predictability.',
            'Counsellors|Calmer days and better conversations.',
            'Marketing teams|Attribution they can finally defend.',
            'Video stories|2-minute watch-and-decide testimonials.',
            '500+ institutions|A voice from every segment we serve.',
        )),
    'reviews' => array('g' => 'proof', 't' => 'Reviews',
        'h1' => 'Rated by the People Who Use It Daily',
        'sub' => 'Independent ratings and detailed reviews from admission teams across platforms - read the praise and the critiques alike.',
        'f' => array(
            'G2 & Capterra|Consistently high ratings across marketplaces.',
            'Ease of use|The most-praised trait - teams onboard in days.',
            'Support quality|24x7 responsiveness reviewers call out by name.',
            'Feature depth|Automation and AI cited as the difference-makers.',
            'Honest critiques|What users want next - and our answers.',
            'Verified reviewers|Real institutions, real deployments.',
        )),
    'awards' => array('g' => 'proof', 't' => 'Awards',
        'h1' => 'Recognition That Backs the Results',
        'sub' => 'Industry awards, analyst mentions and marketplace badges earned by the platform and the teams using it.',
        'f' => array(
            'Product excellence|Best Admission CRM recognitions.',
            'AI innovation|VidyaAI suite honoured for applied AI in education.',
            'Customer success|Support and onboarding award-winners.',
            'High performer badges|Season after season on review platforms.',
            'EdTech ecosystem|Featured across education-industry forums.',
            'Growth story|Recognised among India\'s fastest-growing SaaS.',
        )),

    /* ── RESOURCES ───────────────────────────────────────────────────── */
    'faqs' => array('g' => 'resources', 't' => 'FAQs',
        'h1' => 'Everything You Want to Know',
        'sub' => 'Straight answers on the platform, pricing, implementation, security and AI - and a human on WhatsApp for anything else.',
        'f' => array(
            'What is ExtraaEdge?|An AI-powered Admission CRM built only for education - capture, engage, convert, enrol.',
            'How fast can we go live?|Seven days: data import, setup, AI config and counsellor training included.',
            'Will it work with our website & ads?|Yes - 50+ native integrations plus an open API cover forms, portals and ad platforms.',
            'Is our data safe?|ISO 27001 certified, GDPR-ready, India data residency, full audit logs.',
            'Do small colleges use it?|Yes - plans scale from single institutes to 40-campus groups.',
            'What does the AI actually do?|Answers enquiries 24x7, calls new leads, scores intent and drafts follow-ups.',
        )),
    'api-documentation' => array('g' => 'resources', 't' => 'API Documentation',
        'h1' => 'Build on the ExtraaEdge API',
        'sub' => 'REST APIs and webhooks for leads, activities, stages and analytics - everything your engineering team needs to connect anything.',
        'f' => array(
            'REST endpoints|Create and read leads, activities, stages and users.',
            'Webhooks|Real-time pushes on lead events to your systems.',
            'Auth & scopes|Token-based access with least-privilege scopes.',
            'Sandbox|Test safely against sample data before going live.',
            'Rate limits & SLAs|Documented, generous and predictable.',
            'Code samples|Copy-paste examples for common integrations.',
        )),
    'documentation' => array('g' => 'resources', 't' => 'Documentation',
        'h1' => 'Learn Every Corner of the Platform',
        'sub' => 'Step-by-step guides for admins, counsellors and managers - from first login to advanced automation.',
        'f' => array(
            'Getting started|First-week setup, imports and team onboarding.',
            'Counsellor guides|Daily workflows, worklists and student cards.',
            'Automation cookbook|Recipes for rules, journeys and campaigns.',
            'AI configuration|Tuning VidyaAI calling, chat and scoring.',
            'Admin handbook|Roles, fields, stages and integrations.',
            'Release guides|What\'s new and how to adopt it.',
        )),
    'roi-calculator' => array('g' => 'resources', 't' => 'ROI Calculator',
        'h1' => 'What Would ExtraaEdge Be Worth to You?',
        'sub' => 'Put in your enquiry volume, team size and fees - see projected conversions, savings and payback in minutes.',
        'f' => array(
            'Your numbers in|Enquiries, counsellors, average fee - three inputs.',
            'Conversion upside|Projected extra enrolments at measured lift rates.',
            'Time savings|Hours returned per counsellor per week.',
            'Cost per enrolment|Before and after, side by side.',
            'Payback period|When the platform pays for itself.',
            'Shareable results|Export the model for your leadership review.',
        )),
    'crm-comparison' => array('g' => 'resources', 't' => 'CRM Comparison',
        'h1' => 'ExtraaEdge vs Generic CRMs',
        'sub' => 'An honest, capability-by-capability comparison with generic sales CRMs and legacy education tools - decide with the full picture.',
        'f' => array(
            'Built for education|Courses, batches, counsellors and fees are native - not customised in.',
            'AI that acts|Calls, qualifies and follows up - not just a chatbot bolt-on.',
            'True WhatsApp|Official API with journeys, not a browser plugin.',
            '7-day go-live|Against months of generic-CRM implementation.',
            'Education integrations|Portals and publishers generic CRMs have never heard of.',
            'Admission analytics|Funnel, seat and season metrics out of the box.',
        )),
    'release-notes' => array('g' => 'resources', 't' => 'Release Notes',
        'h1' => 'What\'s New in ExtraaEdge',
        'sub' => 'Every release, documented - new capabilities, improvements and fixes, shipped continuously without downtime.',
        'f' => array(
            'Monthly highlights|The headline capabilities of each cycle.',
            'AI suite updates|VidyaAI models and skills as they improve.',
            'Integration additions|New platforms joining the 50+ catalogue.',
            'Performance notes|Speed and reliability improvements.',
            'Fixes log|Transparent record of what was resolved.',
            'Adopt-it guides|How to switch on each new capability.',
        )),

    /* ── COMPANY ─────────────────────────────────────────────────────── */
    'about-us' => array('g' => 'company', 't' => 'About Us',
        'h1' => 'We Exist to Fix Admissions',
        'sub' => 'Since 2015, ExtraaEdge has built one thing: the AI-powered Admission CRM - trusted today by 500+ institutions across 15+ countries.',
        'f' => array(
            'One mission|Help institutions enrol more students with less chaos.',
            'Education-only DNA|Every feature born from admission teams\' real days.',
            'AI with purpose|Applied AI that answers, calls and converts - not demos.',
            '500+ institutions|Universities to preschools, single campus to forty.',
            '15+ countries|India-born, globally deployed.',
            'Long-term partners|Customers stay because seasons keep improving.',
        )),
    'team' => array('g' => 'company', 't' => 'Team',
        'h1' => 'The People Behind the Platform',
        'sub' => 'Engineers, education specialists and customer-success folks who measure themselves by your admission numbers.',
        'f' => array(
            'Founders|Operators obsessed with education\'s hardest funnel.',
            'Engineering|The team shipping AI that actually does admissions work.',
            'Product|Ex-admission folks designing for real counsellor days.',
            'Customer success|Named partners walking every season with you.',
            'Support|24x7 humans - admission season doesn\'t sleep, neither do we.',
            'Culture|Ownership, candour and customer numbers on the wall.',
        )),
    'careers' => array('g' => 'company', 't' => 'Careers',
        'h1' => 'Build the Future of Admissions',
        'sub' => 'Join a team shipping applied AI used by 500+ institutions - meaningful problems, real ownership and customers who feel the difference.',
        'f' => array(
            'Engineering roles|AI, platform and integrations at scale.',
            'Product & design|Shape how thousands of counsellors work daily.',
            'Sales & marketing|Take a loved product to every institution.',
            'Customer success|Own institutions\' outcomes end to end.',
            'How we work|Small teams, high trust, direct impact.',
            'Open positions|Chat with HR on WhatsApp - we reply fast.',
        )),
    'partners' => array('g' => 'company', 't' => 'Partners',
        'h1' => 'Grow With ExtraaEdge',
        'sub' => 'Referral, reseller and technology partnerships - bring the leading Admission CRM to your education network and win together.',
        'f' => array(
            'Referral partners|Introduce institutions, earn on every win.',
            'Resellers|Sell and serve with our enablement behind you.',
            'Technology partners|Integrate your product into the admission stack.',
            'Education consultants|Add a proven platform to your advisory.',
            'Partner enablement|Training, collateral and named support.',
            'Transparent economics|Clear terms, prompt payouts.',
        )),
    'events' => array('g' => 'company', 't' => 'Events',
        'h1' => 'Meet ExtraaEdge, Online and On Ground',
        'sub' => 'Webinars, conferences, roundtables and product days - learn what winning admission teams do differently.',
        'f' => array(
            'Webinars|Playbooks and product deep-dives, every month.',
            'Industry conferences|Find our booth at education\'s biggest gatherings.',
            'Leadership roundtables|Closed-door sessions for admission heads.',
            'Product days|New capabilities, demoed live with Q&A.',
            'Regional meetups|Customer communities in your city.',
            'On-demand library|Missed one? Every session recorded.',
        )),
    'contact' => array('g' => 'company', 't' => 'Contact',
        'h1' => 'Talk to a Human, Fast',
        'sub' => 'Demos, pricing, support or partnerships - pick any channel; we respond the way we teach admissions to: quickly.',
        'f' => array(
            'Book a demo|30 minutes on your funnel, your courses, your team.',
            'WhatsApp us|Chat on +91 89569 82897 - fastest for quick questions.',
            'Call us|+91 89569 82897, admission-season hours and beyond.',
            'Email|Write to the team; replies within a business day.',
            'Support desk|Existing customers: raise a ticket in-app anytime.',
            'Visit us|Pune, India - come say hello.',
        )),
    'support' => array('g' => 'company', 't' => 'Support',
        'h1' => 'Support That Runs at Admission Speed',
        'sub' => '24x7 help from humans who know admissions - in-app tickets, WhatsApp, guides and a named success partner on bigger plans.',
        'f' => array(
            'In-app tickets|Raise from inside the CRM; tracked to resolution.',
            '24x7 availability|Admission season doesn\'t sleep - neither does support.',
            'WhatsApp support|Real answers on the channel you already use.',
            'Knowledge base|Guides and how-tos for every module.',
            'Named success partner|A human accountable for your outcomes.',
            'Health reviews|Periodic check-ins that tune your setup.',
        )),
    );
}

/* Legacy/menu aliases - the header & footer menus already point at these
   paths, so they render the matching registry page. */
function ee_site_pages_with_aliases() {
    $p = ee_site_pages();
    $p['become-a-partner'] = $p['partners'];
    $p['get-in-touch']     = $p['contact'];
    $p['integrations']     = $p['products/integrations'];
    $p['solutions/universities']        = $p['industries/higher-education-crm'];
    $p['solutions/colleges']            = $p['industries/higher-education-crm'];
    $p['solutions/schools']             = $p['industries/school-crm'];
    $p['solutions/coaching-institutes'] = $p['industries/coaching-institute-crm'];
    $p['solutions/edtech']              = $p['industries/edtech-crm'];
    $p['solutions/study-abroad']        = $p['industries/overseas-crm'];
    foreach (array('executive-dashboard','admission-analytics','marketing-analytics',
                   'lead-analytics','funnel-analytics','custom-reports') as $ee_an) {
        $p['products/' . $ee_an] = $p['analytics/' . $ee_an];
    }
    return $p;
}

/* Related pages: same-group siblings, excluding self. */
function ee_site_page_related($key, $max = 6) {
    $all = ee_site_pages();
    if (!isset($all[$key])) return array();
    $g = $all[$key]['g']; $out = array();
    foreach ($all as $k => $p) {
        if ($k === $key || $p['g'] !== $g) continue;
        $out[$k] = $p['t'];
        if (count($out) >= $max) break;
    }
    return $out;
}
